# 1. Configuración Inicial

In [1]:
# Librerias
import pandas as pd
import numpy as np
import os
import pathlib
import re
from pathlib import Path
import subprocess, shutil

In [2]:
# --- Papermill parameters ---

# Directorio de entrada (OneDrive sincronizado por Actions)
RAW_DIR = os.getenv("RAW_DIR", "data/raw")

# Ruta de salida del parquet optimizado
OUTPUT_PARQUET = os.getenv("OUTPUT_PARQUET", "data/summary.parquet")

# Ruta de salida del historico mensual (evolucion del tiempo promedio de ventas)
OUTPUT_HIST_PARQUET = os.getenv("OUTPUT_HIST_PARQUET", "data/historico_mensual.parquet")

In [3]:
# Columnas minimas que necesita la app Streamlit
COLS_APP = [
    "CODIGO", "PRODUCTO",
    "CATEGORIA", "SUBCATEGORIA", "MARCA", "COMERCIO",
    "margen_bruto_%",                # % (ej. 43.6) — mantén misma convención que en la app
    "metrica_margen_bruto",          # Perdida / Beneficio Bajo / Medio / Alto
    "beneficio_promedio_por_producto",
    "STOCK",
    "unidades_vendidas_totales",
]

# Columnas de diagnostico del libro de movimientos.
# Documentan que se asumio para cada producto; ninguna correccion es silenciosa.
COLS_DIAG = [
    "CALIDAD_DATOS",        # OK / APERTURA_ESTIMADA / SALIDA_NO_REGISTRADA / NO_INVENTARIABLE / SIN_MOVIMIENTOS
    "STOCK_APERTURA_EST",   # unidades inyectadas como capa inicial
    "AJUSTE_SALIDA",        # unidades retiradas para cuadrar contra el inventario
    "NEGATIVO_RESIDUAL",    # sigue habiendo stock negativo aun despues del ajuste
    "SIN_COMPRAS",          # nunca tuvo una compra registrada
    "VENTA_ANTICIPADA",     # 1a transaccion es venta y la compra llega poco despues
]

COLS_APP = COLS_APP + COLS_DIAG

# Metricas de antiguedad (FIFO), cobertura y valor del inventario.
COLS_FIFO = [
    "COSTO",                    # costo unitario del inventario
    "VALOR_STOCK",              # STOCK * COSTO: capital inmovilizado
    "ANTIGUEDAD_STOCK_DIAS",    # dias que lleva parado lo que hay, ponderado por unidad
    "DIAS_ESTANTERIA_VENDIDO",  # dias que estuvo en tienda lo ya vendido, ponderado por unidad
    "COBERTURA_DIAS",           # cuanto dura el stock al ritmo de venta reciente
    "UNIDADES_SIN_CAPA",        # salidas que el libro no pudo respaldar
    "ROTACION",                 # bucket unificado sobre ANTIGUEDAD_STOCK_DIAS
    "VALOR_0_60", "VALOR_61_120", "VALOR_121_180", "VALOR_MAS_180",
    # Para decidir sobre productos agotados, donde cobertura y antiguedad no aplican
    "MESES_CON_STOCK",          # meses en que el producto SI tuvo existencias
    "MESES_AGOTADO",            # meses consecutivos en cero al cierre de los datos
    "DISPONIBILIDAD_PCT",       # % de su vida en que estuvo disponible
    "VENTA_MENSUAL_EN_STOCK",   # unidades/mes contadas solo sobre meses con stock
    "UNIDADES_PERDIDAS_EST",    # rotacion en disponibilidad x meses agotado
]

COLS_APP = COLS_APP + COLS_FIFO

# Cortes unicos de antiguedad. Se usan en TODO el proyecto: KPI, graficos,
# serie mensual y descargas. No definir cortes distintos en otro lado.
CORTES_DIAS   = [0, 60, 120, 180, float("inf")]
ETIQUETAS_DIAS = ["Estrella", "Optimo", "Tomar Accion", "Tomar Accion Urgente"]

# Ventana para la cobertura movil (dias hacia atras desde el corte de datos).
VENTANA_COBERTURA = 180

In [4]:
# --- Asegurar que el cwd sea la raíz del proyecto (no otra ubicacion) ---
nb_dir = pathlib.Path().resolve()
# si estamos dentro de /notebooks, subir un nivel
if nb_dir.name.lower() == "notebooks":
    os.chdir(nb_dir.parent)
print("cwd ->", os.getcwd())

cwd -> D:\Jupyter_Notebooks\proyecto-restauradores

In [5]:
"""
Autodescubrimiento y validacion de los archivos de entrada.

Nomenclatura esperada en la carpeta de OneDrive:
    ventas_MM_YYYY.xlsx        (MM con DOS digitos: ventas_03_2026, no ventas_3_2026)
    compras_MM_YYYY.xlsx       (debe existir el del MISMO mes que ventas)
    inventario_YYYYMMDD.xlsx
    costos_fijos_historico.xlsx

Cualquier archivo que se salga del formato se reporta con nombre y motivo, en
lugar de ignorarse en silencio o reventar con un error indescifrable.
"""

RAW = Path(RAW_DIR)
if not RAW.exists():
    raise FileNotFoundError(f"No existe la carpeta de entrada: {RAW.resolve()}")

pat_v = re.compile(r"ventas_(\d{2})_(\d{4})\.xlsx$", re.IGNORECASE)
pat_c = re.compile(r"compras_(\d{2})_(\d{4})\.xlsx$", re.IGNORECASE)
pat_i = re.compile(r"inventario_(\d{8})\.xlsx$", re.IGNORECASE)

PATRONES = {"ventas": pat_v, "compras": pat_c, "inventario": pat_i}
EJEMPLOS = {
    "ventas": "ventas_MM_YYYY.xlsx (ej. ventas_03_2026.xlsx)",
    "compras": "compras_MM_YYYY.xlsx (ej. compras_03_2026.xlsx)",
    "inventario": "inventario_YYYYMMDD.xlsx (ej. inventario_20260331.xlsx)",
}

# --- Detectar archivos con nombre casi correcto, que si no se avisan quedan
# --- fuera del analisis sin que nadie lo note.
# Se valida el NOMBRE, no la extension: un .xls es entrada legitima porque el
# workflow lo convierte a .xlsx antes de llegar aqui.
PATRONES_NOMBRE = {
    "ventas": re.compile(r"ventas_\d{2}_\d{4}$", re.IGNORECASE),
    "compras": re.compile(r"compras_\d{2}_\d{4}$", re.IGNORECASE),
    "inventario": re.compile(r"inventario_\d{8}$", re.IGNORECASE),
}

descartados = []
for f in sorted(RAW.iterdir()):
    if not f.is_file() or f.name.startswith("~$"):
        continue
    if f.suffix.lower() not in (".xls", ".xlsx"):
        continue
    stem = f.stem.lower()
    if stem.startswith("costos_fijos_historico"):
        continue
    for familia, patron in PATRONES_NOMBRE.items():
        if stem.startswith(familia) and not patron.match(f.stem):
            descartados.append((f.name, EJEMPLOS[familia]))
            break

if descartados:
    detalle = "\n".join(f"    - {n}   ->  se esperaba {e}" for n, e in descartados)
    raise ValueError(
        "Hay archivos en la carpeta de ingesta cuyo nombre no cumple el formato, "
        "y por eso NO se estarian procesando:\n"
        f"{detalle}\n"
        "  Corrige los nombres en OneDrive y vuelve a lanzar el ETL. "
        "Ojo con el mes: siempre dos digitos (03, no 3)."
    )

ventas_files     = [p for p in RAW.glob("*.xlsx") if pat_v.match(p.name)]
compras_files    = [p for p in RAW.glob("*.xlsx") if pat_c.match(p.name)]
inventario_files = [p for p in RAW.glob("*.xlsx") if pat_i.match(p.name)]

_encontrados = sorted(p.name for p in RAW.glob("*.xlsx"))
for familia, lista in [("ventas", ventas_files), ("compras", compras_files),
                       ("inventario", inventario_files)]:
    if not lista:
        raise FileNotFoundError(
            f"No hay ningun archivo de {familia} con el formato {EJEMPLOS[familia]} "
            f"en {RAW.resolve()}.\n"
            f"  Archivos .xlsx encontrados: {_encontrados or 'ninguno'}"
        )

# --- Se trabaja con el mes de ventas mas reciente ---
def _mes_de(p, patron):
    m = patron.match(p.name)
    return (int(m.group(2)), int(m.group(1)))   # (anio, mes)

ventas_path = sorted(ventas_files, key=lambda p: _mes_de(p, pat_v))[-1]
_mes_objetivo = pat_v.match(ventas_path.name).groups()

_compras_del_mes = [p for p in compras_files if pat_c.match(p.name).groups() == _mes_objetivo]
if not _compras_del_mes:
    mm, yyyy = _mes_objetivo
    raise FileNotFoundError(
        f"Existe {ventas_path.name} pero falta su compra del mismo periodo "
        f"(compras_{mm}_{yyyy}.xlsx).\n"
        f"  Compras disponibles: {sorted(p.name for p in compras_files)}\n"
        "  Los dos reportes deben cubrir el mismo corte para que los calculos cuadren."
    )
compras_path = _compras_del_mes[0]

inventario_path = sorted(inventario_files, key=lambda p: pat_i.match(p.name).group(1))[-1]

costos_path = RAW / "costos_fijos_historico.xlsx"
if not costos_path.exists():
    _cand = [p.name for p in RAW.glob("*.xlsx") if "costos" in p.name.lower()]
    raise FileNotFoundError(
        f"Falta costos_fijos_historico.xlsx en {RAW.resolve()}. "
        "Sin el no se puede repartir el costo fijo y la utilidad neta seria falsa.\n"
        f"  Archivos parecidos encontrados: {_cand or 'ninguno'}"
    )

print("VENTAS :", ventas_path.name)
print("COMPRAS:", compras_path.name)
print("INV    :", inventario_path.name)
print("COSTOS :", costos_path.name)

ventas_df     = pd.read_excel(ventas_path, engine="openpyxl")
compras_df    = pd.read_excel(compras_path, engine="openpyxl")
inventario_df = pd.read_excel(inventario_path, engine="openpyxl")

VENTAS : ventas_11_2025.xlsx
COMPRAS: compras_11_2025.xlsx
INV    : inventario_20251107.xlsx

In [6]:
# Función para convertir .xls a .xlsx usando LibreOffice (soffice --headless)
def ensure_xlsx(path: Path) -> Path:
    """
    Si 'path' es .xls, lo convierte a .xlsx con LibreOffice (soffice --headless)
    y devuelve la ruta .xlsx. Si ya es .xlsx, devuelve el original.
    """
    path = Path(path)
    if path.suffix.lower() == ".xlsx":
        return path
    if path.suffix.lower() != ".xls":
        raise ValueError(f"Extensión no soportada: {path.suffix} (esperaba .xls o .xlsx)")

    xlsx_path = path.with_suffix(".xlsx")

    # Buscar 'soffice' (PATH o rutas típicas en Windows)
    candidatos = [
        shutil.which("soffice"),
        r"C:\Program Files\LibreOffice\program\soffice.exe",
        r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
    ]
    soffice = next((p for p in candidatos if p and Path(p).exists()), None)

    if not soffice:
        raise RuntimeError(
            "No se encontró LibreOffice (soffice). "
            "Instálalo o ajusta la ruta en ensure_xlsx."
        )

    cmd = [soffice, "--headless", "--convert-to", "xlsx", "--outdir", str(path.parent), str(path)]
    subprocess.check_call(cmd)

    if not xlsx_path.exists():
        raise RuntimeError(f"No se generó {xlsx_path.name}. Revisa el archivo fuente {path.name}.")
    return xlsx_path

In [7]:
# Conversión .xls -> .xlsx si hace falta
ventas_path     = ensure_xlsx(ventas_path)
compras_path    = ensure_xlsx(compras_path)
inventario_path = ensure_xlsx(inventario_path)

In [8]:
def agregar_variable(
    df_origen,
    df_destino,
    nombre_variable,
    nombre_destino=None,
    key='CODIGO',
    inplace=False
):
    """
    Extrae la columna `nombre_variable` de df_origen y la añade al DataFrame destino,
    devolviendo una copia por defecto (no modifica el df_destino original).

    Parámetros
    ----------
    df_origen : pandas.DataFrame
        DataFrame que contiene la variable a extraer.
    df_destino : pandas.DataFrame
        DataFrame al que se añadirá la nueva columna (o su copia).
    nombre_variable : str
        Nombre de la columna en df_origen que queremos copiar.
    nombre_destino : str, opcional
        Nombre de la columna en el DataFrame resultante. Si no se indica, se usa nombre_variable.
    key : str, por defecto 'CODIGO'
        Nombre de la columna clave en ambos DataFrames para hacer el mapeo.
    inplace : bool, por defecto False
        Si True, modifica df_destino en sitio; si False, trabaja sobre una copia y deja
        el df_destino intacto.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con la nueva columna añadida.
    """
    if nombre_destino is None:
        nombre_destino = nombre_variable

    # Nos quedamos con la primera aparición de cada clave en el origen
    df_unicas = df_origen.drop_duplicates(subset=[key], keep='first')
    # Creamos el mapping clave → valor
    mapping = df_unicas.set_index(key)[nombre_variable]

    # Elegimos destino: copia o el original según inplace
    df_res = df_destino if inplace else df_destino.copy()

    # Asignamos la nueva columna
    df_res[nombre_destino] = df_res[key].map(mapping)

    return df_res

## 1.1. Inventario

In [9]:
# Skip the unnecessary rows and set appropriate headers based on the structure
inventario = pd.read_excel(inventario_path, engine="openpyxl", skiprows=3)

# Creamos una nueva columna para CATEGORIAS, en el excel cada categoria se encuentra como encabezado. Para mejor manejo de datos creamos esta nueva columna
inventario['CATEGORIA'] = inventario['CODIGO'].where(inventario['DESCRIPCION'].isna()).ffill()

# ELiminamos la categoria SIN CATEGORIA
inventario = inventario[inventario['CATEGORIA'] != 'SIN CATEGORIA']

# Luego creamos los nombres para las columnas
nombre_columnas = [
    "CODIGO", "PRODUCTO", "MARCA", "STOCK", 
    "COSTO", "TOTAL", "PVP", "VALOR1", "CATEGORIA"
]

# Asignamos los nuevos nombres de columnas
inventario.columns = nombre_columnas

In [10]:
# 1. Elimina la columna VALOR1
inventario = inventario.drop(['VALOR1'], axis=1, errors='ignore')

# 2. Elimina las filas con valor nulo
inventario = inventario.dropna(how='any').reset_index(drop=True)

# 3. Eliminar duplicados. Estos duplicados corresponden al stock de TALLER, ya que el sistema arroja todos los codigos para cada comercio
# Ordenamos para priorizar registros con stock > 0
inventario = inventario.sort_values(by=['CODIGO', 'STOCK'], ascending=[True, False])
# Eliminar duplicados manteniendo la fila con mayor stock (cualquier stock >0 sobre stock=0)
inventario = inventario.drop_duplicates(subset='CODIGO', keep='first')

# 4. cambiar valores de STOCK, COSTO Y TOTAL negativo a stock 0 
inventario[['STOCK', 'COSTO', 'TOTAL']] = inventario[['STOCK', 'COSTO', 'TOTAL']].clip(lower=0)

# 5. Eliminar los FUERA DE INVENTARIO
inventario = inventario[
    ~inventario['PRODUCTO']
      .astype(str)
      .str.contains('FUERA DE INVENTARIO|FUERA DE SERVICIO|FUERA DE INEVENTARIO', case=False, na=False)
].reset_index(drop=True)

## 1.2. Compras

In [11]:
# skiprows es para ignorar las primeras filas del excel.
compras = pd.read_excel(compras_path, skiprows=4)

# Luego creamos los nombres para las columnas
nombre_columnas = [
    "CODIGO", "FECHA", "PROVEEDOR", "TIPO", 
    "CANTIDAD", "PRODUCTO", "FECHA_SISTEMA", "COSTO_TOTAL_SIN_IVA"
]

# Asignamos los nuevos nombres de columnas
compras.columns = nombre_columnas

In [12]:
# 1. Elminamos observaciones/filas de compras que NO SON PRODUCTOS como TRANSPORTE, SUMINISTROS, OTROS GASTOS, etc
# Luego eliminamos todos los valores por debajo de {SERVICIO} que pertenecen a valores por servicio de transporte
# Compruebo que exista la columna que busco
if 'CODIGO' not in compras.columns:
    raise KeyError("La columna 'CODIGO' no existe en el DataFrame.")

# 2) Creo la máscara para detectar el marcador
mask = compras['CODIGO'].eq('SERVICIOS')

# 3) Sólo si aparece “SERVICIOS”, corto hasta antes de esa fila
if mask.any():
    # idxmax() me da la etiqueta (index label) de la primera True
    first_label = mask.idxmax()
    # get_loc() traduce esa etiqueta a posición entera
    pos = compras.index.get_loc(first_label)
    # slice hasta pos (excluyendo la fila de 'SERVICIOS') y limpio el índice
    compras = compras.iloc[:pos].reset_index(drop=True)

# 2. Eliminar las compras con "FUERA DE INVENTARIO"
compras = compras[
    ~compras['PRODUCTO']
      .astype(str)
      .str.contains('FUERA DE INVENTARIO|FUERA DE SERVICIO|FUERA DE INEVENTARIO', case=False, na=False)
].reset_index(drop=True)

# 3. Elimina la columna FECHA SISTEMA
compras = compras.drop(['FECHA_SISTEMA'], axis=1, errors='ignore')

# 4. Elimina las filas con valor nulo
compras = compras.dropna(how='any').reset_index(drop=True)

# 5. Agrega variable COSTO_UNITARIO_SIN_IVA
compras['COSTO_UNITARIO_SIN_IVA'] = compras.COSTO_TOTAL_SIN_IVA/compras.CANTIDAD

# 6. Cambiar costo de productos que tienen valores NEGATIVOS. Cambiar a costo 0
compras['COSTO_UNITARIO_SIN_IVA'] = compras['COSTO_UNITARIO_SIN_IVA'].clip(lower=0)

# 7. Agregamos 'CATEGORIA' a compras desde df inventario:
compras = agregar_variable(
    df_origen = inventario,
    df_destino = compras,
    nombre_variable='CATEGORIA'
)

# 8. Eliminar la categoria "SIN CATEGORIA"
compras = compras[compras['CATEGORIA'] != 'SIN CATEGORIA']

# DOCUMENTACION COMPRAS

#### ***** *CORREGIR LA VARIABLE COSTO DEL REPORTE DE COMPRAS!!!*
1. **COSTO_TOTAL_SIN_IVA**: Es el costo total (cantidad * costo_unitario) SIN IVA de cada factura de compra realizada. El costo NO corresponde al costo que hay en las facturas. Esta tomando el costo sin descuento de las facturas
2. **COSTO_UNITARIO_SIN_IVA**: Es el costo UNITARIO SIN IVA de cada producto

## 1.3. Ventas

In [13]:
# skiprows es para ignorar las primeras filas del excel.
ventas = pd.read_excel(ventas_path, skiprows=4)

# Luego creamos los nombres para las columnas
nombre_columnas_ventas = [
    "FECHA", "CLIENTE", "FACTURA", "HORA", "CATEGORIA", "CODIGO", 
    "PRODUCTO", "CANTIDAD", "V_UNITARIO", "DESCUENTO", "IVA", 
    "V_TOTAL", "COSTO", "VENDEDOR", "VALOR_1", "VALOR_2"
]

# Asignamos los nuevos nombres de columnas
ventas.columns = nombre_columnas_ventas

In [14]:
# 1. Elimina las ultimas dos columnas
ventas = ventas.iloc[:, :-2]

# 2. Eliminar las ventas con "FUERA DE INVENTARIO"
ventas = ventas[
    ~ventas['PRODUCTO']
      .astype(str)
      .str.contains('FUERA DE INVENTARIO|FUERA DE SERVICIO|FUERA DE INEVENTARIO', case=False, na=False)
].reset_index(drop=True)

# 3. Elimina las filas con valor nulo
ventas = ventas.dropna(how='any').reset_index(drop=True)

# 4. Eliminar la categoria "SIN CATEGORIA"
ventas = ventas[ventas['CATEGORIA'] != 'SIN CATEGORIA']

# 5. Convertir FECHA en datetimeindex
ventas['FECHA'] = pd.to_datetime(ventas['FECHA'], format='%d/%m/%Y')

# 6. Cambiar costo de productos que tienen valores NEGATIVOS. Cambiar a costo 0
ventas['COSTO'] = ventas['COSTO'].clip(lower=0)

"""
# 6. Incluir la variable COSTO desde el DF compras
# Establecer un costo promedio del DF compras para cada producto de ventas. Si algun producto de ventas no esta en el df de compras, que le añada el valor de COSTO del DF ventas

avg_cost = compras.groupby('CODIGO', as_index=False)['COSTO_UNITARIO_SIN_IVA'] \
                  .mean() \
                  .set_index('CODIGO')['COSTO_UNITARIO_SIN_IVA']

# 7. Mapea ese promedio en ventas; donde falte, usa COSTO_VENTA
ventas['COSTO_PROMEDIO_UNITARIO'] = (
    ventas['CODIGO']
    .map(avg_cost)                    # trae el costo promedio de compras
    .fillna(ventas['COSTO'])          # si no existe, usa el costo de venta
)

# 8. Eliminar variable COSTO (Obsoleto)
# Se establece como costo oficial a la variable COSTO_PROMEDIO, ya que la variable COSTO del DF ventas coge solo el ultimo costo del sistema
#ventas = ventas.drop(['COSTO'], axis=1, errors='ignore')
"""

# 9. Crear categoria COMERCIO
ventas['COMERCIO'] = ventas['CATEGORIA'].map({
    'MAQUINARIA': 'ALMACEN',
    'ACCESORIO': 'ALMACEN',
    'REPUESTO': 'TALLER',
    'SERVICIO': 'TALLER'
})

# En lugar de tomar la variable COSTO_PROMEDIO del df compras, voy a utilizar la variable COSTO del df ventas (MODIFICADO)
ventas['COSTO_TOTAL_UNITARIO'] = ventas.COSTO * ventas.CANTIDAD
ventas['INGRESO_TOTAL_SIN_IVA'] = ventas.V_UNITARIO * ventas.CANTIDAD
ventas['UTILIDAD'] = ventas['INGRESO_TOTAL_SIN_IVA'] - ventas['COSTO_TOTAL_UNITARIO']

# 10. Se eliminan las ventas que han tenido UTILIDAD<0. Cosas como servicio de transporte, varillas, mangueras, etc  
ventas_limpio = ventas[ventas['UTILIDAD'] > 0]
#Como resultado se eliminaro 636 filas/observaciones de ventas que fueron obsequi y ventas con anomalias en cuanto a la utilidad

# OJO 
se esta tomando el COSTO de las ventas porque el COSTO que aparece en el reporte de compras en un costo donde NO se consideran los descuentos de la factura de compra. Anfibius debe corregir. Cuando Anfibius corrija eso, se puede usa el COSTO de compras para determinar el COSTO_PROMEDIO segun el codigo de arriba

In [15]:
def filtrar_por_palabras(df: pd.DataFrame,
                         column: str,
                         keyword: str,
                         case: bool = False) -> pd.DataFrame:
    """
    Filtra las filas de `df` manteniendo solo aquellas donde
    el texto en `column` contenga `keyword`, y devuelve un
    DataFrame sin códigos repetidos (solo primera aparición).

    Parámetros
    ----------
    df : pd.DataFrame
        DataFrame de entrada.
    column : str
        Nombre de la columna en la que buscar el keyword.
    keyword : str
        Texto o patrón a buscar dentro de la columna.
    case : bool, opcional
        Si True, la búsqueda distinguirá mayúsculas/minúsculas
        (por defecto False).

    Devuelve
    -------
    pd.DataFrame
        Subconjunto de filas donde df[column] contiene keyword,
        sin duplicados en la columna 'CODIGO'.
    """
    # Nos aseguramos de tratar la columna como string
    texto = df[column].astype(str)
    # Creamos la máscara de True/False
    mask = texto.str.contains(keyword, case=case, na=False)
    
    # Filtramos y hacemos copia para evitar SettingWithCopyWarning
    productos_con_filtro = df[mask].copy()
    
    # Eliminamos duplicados en 'CODIGO', quedándonos con la primera aparición
    productos_unicos = productos_con_filtro.drop_duplicates(
        subset=['CODIGO'],
        keep='first'
    )
    
    # Mensaje informativo
    if productos_unicos.empty:
        print(f"No se encontró ningún producto con la palabra '{keyword}'.")
    else:
        print(f"Se encontraron {len(productos_unicos)} productos con '{keyword}'")
    
    return productos_unicos

In [16]:
maqs = ventas[ventas['CATEGORIA'] == 'MAQUINARIA']
acss = ventas[ventas['CATEGORIA'] == 'ACCESORIO']

# Productos de ACCESORIOS dentro de MAQUINARIAS
broca = filtrar_por_palabras(maqs, 'PRODUCTO', 'BROCA')
disco = filtrar_por_palabras(maqs, 'PRODUCTO', 'DISCO')

#Productos de MAQUINARIAS dentro de ACCESORIOS
rotomartillo = filtrar_por_palabras(acss, 'PRODUCTO', 'ROTOMARTILLO')
taladro = filtrar_por_palabras(acss, 'PRODUCTO', 'TALADRO')
amoladora = filtrar_por_palabras(acss, 'PRODUCTO', 'AMOLADORA')
soldadora = filtrar_por_palabras(acss, 'PRODUCTO', 'SOLDADORA')

#rotomartillo[rotomartillo.CODIGO == 'R431']

Se encontraron 7 productos con 'BROCA'
Se encontraron 8 productos con 'DISCO'
Se encontraron 11 productos con 'ROTOMARTILLO'
Se encontraron 20 productos con 'TALADRO'
Se encontraron 4 productos con 'AMOLADORA'
Se encontraron 9 productos con 'SOLDADORA'

# DOCUMENTACION VENTAS

Descripcion de cada variable del df ventas:

1. **V_UNITARIO**: Corresponde al valor unitario de cada producto SIN IVA
2. **COSTO**: Es el costo UNITARIO de cada producto SIN IVA
3. **V_TOTAL**: Valor total de la venta INCLUIDO IVA

- IMPORTANTE: Corregir productos que estan mal ingresados. Productos que se venden "al granel" como varillas, mangueras, sierras para caladora, etc. Corregir productos mal CLASIFICADOS en categoria maquinaria, accesorios, repuestos, servicio
- PROHIBIDO: No cambiar los costos manualmente, solo modificar EQUIVALENCIAS en Anfibius

Ejemplos: 

- Cambiar en el sistema la categoria para "SELLO MECANICO" y 'ESCUADRA DACERO INOX. 12 ANGULO RECTO 90 WADFOW WSR2930' debe ser cambiado a CATEGORIA - REPUESTO y ACCESORIO respectivamente

In [17]:
# Exportar archivos limpios
"""
ventas.to_excel(
    'Data_limpia/ventas_limpio.xlsx',
    index=False,            # No incluye la columna de índice
)

compras.to_excel(
    'Data_limpia/compras_limpio.xlsx',
    index=False,            # No incluye la columna de índice
)

inventario.to_excel(
    'Data_limpia/inventario_112025.xlsx',
    index=False,            # No incluye la columna de índice
)
"""

"\nventas.to_excel(\n    'Data_limpia/ventas_limpio.xlsx',\n    index=False,            # No incluye la columna de índice\n)\n\ncompras.to_excel(\n    'Data_limpia/compras_limpio.xlsx',\n    index=False,            # No incluye la columna de índice\n)\n\ninventario.to_excel(\n    'Data_limpia/inventario_112025.xlsx',\n    index=False,            # No incluye la columna de índice\n)\n"

# 2. ANALISIS

# 2.1. TIEMPO

Lo que vamos a hacer es determinar el tiempo promedio de venta de cada producto tomando en cuenta la fecha que fue comprado y la fecha que fue vendido. Para esto seguimos el siguiente procedimiento:
1. Ordanamos por codigo y fecha los datasets de ventas y compras
2. Creamos una variable para distinguir que pertenece a una COMPRA o a una VENTA
3. Se crea un DF que combine las ventas y compras en orden cronologico (FECHA, CODIGO, CANTIDAD, TIPO_TRANSACCION)
4. Se crea un flujo de trabajo para determinar las distintas situaciones encontradas dentro del sistema de facturacion de acuerdo a una tabla de condiciones (ver excel Condiciones_Calculo_Tiempo_Ventas.xlsx)

In [18]:
# 1. Ordenamos los datasets de compras y ventas
compras_df = compras.sort_values(by=['CODIGO', 'FECHA']).reset_index(drop=True)
ventas_df = ventas_limpio.sort_values(by=['CODIGO', 'FECHA']).reset_index(drop=True)

# 2. Creamos una variable para distinguir que pertenece a una COMPRA o a una VENTA
compras_df['TIPO_TRANSACCION'] = 'COMPRA'
ventas_df['TIPO_TRANSACCION'] = 'VENTA'

# Seleccionamos las columnas de interes
compras_df_filtro = compras_df[['FECHA', 'CODIGO', 'CANTIDAD', 'TIPO_TRANSACCION']]
ventas_df_filtro = ventas_df[['FECHA', 'CODIGO', 'CANTIDAD', 'TIPO_TRANSACCION']]

# 3. Combinamos los DF de ventas y compras
combined_df = pd.concat([compras_df_filtro, ventas_df_filtro]).sort_values(by=['CODIGO', 'FECHA']).reset_index(drop=True)

In [ ]:
"""
Fecha de corte de los datos: el ultimo movimiento registrado en el libro.

TODO el proyecto se ancla a esta fecha y NO a la fecha de ejecucion. Si no fuera
asi, volver a correr el pipeline sobre los mismos archivos daria numeros
distintos: los dias parados creceran solos y, peor, el reparto de costos fijos
sumaria meses sin ventas contra los mismos ingresos, bajando la utilidad
reportada sin que hubiera pasado nada en el negocio.
"""

FECHA_CORTE_DATOS = pd.to_datetime(combined_df["FECHA"]).max().normalize()
HOY_REAL = pd.Timestamp.today().normalize()
MESES_DESFASE = (HOY_REAL.to_period("M") - FECHA_CORTE_DATOS.to_period("M")).n

print(f"Fecha de corte de los datos : {FECHA_CORTE_DATOS:%Y-%m-%d}")
print(f"Fecha de ejecucion          : {HOY_REAL:%Y-%m-%d}")
print(f"Desfase                     : {MESES_DESFASE} meses")

# Umbral de aviso. No se corta la ejecucion: los reportes se suben a mano y un
# retraso no invalida el analisis, pero tiene que verse.
MESES_DESFASE_AVISO = 2

if MESES_DESFASE > MESES_DESFASE_AVISO:
    print()
    print("=" * 70)
    print(f"AVISO: los datos tienen {MESES_DESFASE} meses de antiguedad.")
    print(f"  Ultimo movimiento    : {FECHA_CORTE_DATOS:%Y-%m-%d}")
    print(f"  Archivo de ventas    : {ventas_path.name}")
    print(f"  Archivo de inventario: {inventario_path.name}")
    print("  El panel va a mostrar la foto de esa fecha, no la de hoy.")
    print("  Sube los reportes actualizados a la carpeta de ingesta de OneDrive.")
    print("=" * 70)

# Se deja registrado para que el dashboard muestre la fecha real de los datos
# y no la de la ultima corrida del pipeline, que son cosas distintas.
_version = Path("data/data_version.txt")
_version.parent.mkdir(parents=True, exist_ok=True)
_version.write_text(
    f"data_cut={FECHA_CORTE_DATOS:%Y-%m-%d}\n"
    f"meses_desfase={MESES_DESFASE}\n"
    f"archivo_ventas={ventas_path.name}\n"
    f"archivo_inventario={inventario_path.name}\n",
    encoding="utf-8",
)

In [19]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65839 entries, 0 to 65838
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FECHA             65839 non-null  datetime64[ns]
 1   CODIGO            65839 non-null  object
 2   CANTIDAD          65839 non-null  float64
 3   TIPO_TRANSACCION  65839 non-null  object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 2.0+ MB

In [20]:
# Comprobacion de organizacion de ventas por producto
combined_df[combined_df.CODIGO == '4082']

                    FECHA CODIGO  CANTIDAD TIPO_TRANSACCION
20227 2023-05-12 12:16:00   4082       2.0           COMPRA
20228 2023-09-11 00:00:00   4082       1.0            VENTA
20229 2023-10-04 15:54:00   4082       3.0           COMPRA
20230 2023-11-27 00:00:00   4082       1.0            VENTA
20231 2023-12-22 00:00:00   4082       1.0            VENTA
20232 2024-01-29 10:34:00   4082       2.0           COMPRA
20233 2024-02-05 00:00:00   4082       1.0            VENTA
20234 2024-03-23 00:00:00   4082       1.0            VENTA
20235 2024-03-25 09:01:00   4082       4.0           COMPRA
20236 2024-06-03 00:00:00   4082       1.0            VENTA
20237 2024-09-06 00:00:00   4082       1.0            VENTA
20238 2024-10-02 00:00:00   4082       1.0            VENTA
20239 2024-12-06 00:00:00   4082       1.0            VENTA
20240 2025-02-11 12:44:00   4082       2.0           COMPRA
20241 2025-04-22 00:00:00   4082       1.0            VENTA
20242 2025-05-05 00:00:00   4082       1.0            VENTA
20243 2025-05-14 15:26:00   4082       3.0           COMPRA
20244 2025-05-27 00:00:00   4082       1.0            VENTA
20245 2025-07-21 00:00:00   4082       1.0            VENTA

AÑADIR UNA VARIABLE o una lista o un diccionario que contenga los valores de stock de cada codigo. Luego verificar si el codigo tiene stock>0, que cuente los dias desde la ultima venta hasta la fecha de hoy y luego incluya este conteo como una operacion mas y calcule el promedio tomando en cuenta esto ultimo. Tomar en cuenta solo los casos que tienen al menos una venta y que tienen stock>0

In [21]:
# 4. Flujo de trabajo para determinar el tiempo de venta para cada producto. Se detalla por categoria los diferentes casos que se han observado 
# en las ventas del sistema de facturacion. Ver el archivo excel para conocer como se clasificaron los tipos de casos de ventas.

# NOTA: PROMEDIO_DIAS_VENTAS ya NO se exporta al dashboard; lo reemplazo la
# antiguedad FIFO (ANTIGUEDAD_STOCK_DIAS). Esta celda se conserva porque
# 'tiempo_promedio_ventas' es el marco base sobre el que se arma 'resumen_final'
# (aporta CODIGO, PRODUCTO, CATEGORIA, COMERCIO y STOCK).

# Parámetros fijos
STORE_OPEN = pd.Timestamp('2020-10-01')
TODAY      = FECHA_CORTE_DATOS   # fecha de los datos, NO la de ejecucion

# Asegurarnos de que la fecha es datetime
combined_df['FECHA']    = pd.to_datetime(combined_df['FECHA'])
inventario['CODIGO']    = inventario['CODIGO'].astype(combined_df['CODIGO'].dtype)

# 1) Construir un mapeo CODIGO → stock actual
stock_dict = inventario.set_index('CODIGO')['STOCK'].to_dict()

results = []

for codigo, group in combined_df.groupby('CODIGO'):
    group = group.sort_values('FECHA').reset_index(drop=True)
    tipos = group['TIPO_TRANSACCION'].tolist()
    fechas = group['FECHA'].tolist()

    n_compra = tipos.count('COMPRA')
    n_venta  = tipos.count('VENTA')
    diffs    = []

    # consulto stock para este código (0 si no existe en inventario)
    stock = stock_dict.get(codigo, 0)

    # 1) Caso 1. Hay compras y ventas
    if n_compra > 0 and n_venta > 0:
        # Sólo COMPRA→VENTA y VENTA→VENTA
        for i in range(1, len(tipos)):
            prev, curr = tipos[i-1], tipos[i]
            if (prev=='COMPRA' and curr=='VENTA') or (prev=='VENTA' and curr=='VENTA'):
                diffs.append((fechas[i] - fechas[i-1]).days)

        # Si tiene stock >0 y al menos una venta, incluyo tiempo desde última venta hasta hoy
        if stock > 0 and n_venta > 0:
            last_sale = group.loc[group['TIPO_TRANSACCION']=='VENTA', 'FECHA'].max()
            diffs.append((TODAY - last_sale).days)

        if diffs:
            avg_days = np.mean(diffs)
            max_days = np.max(diffs)
            min_days = np.min(diffs)
            ops      = len(diffs)
        else:
            avg_days = max_days = min_days = 0
            ops = 0
        obs = 'compra->venta y venta->venta'

    # 2) Caso 2. Sólo compras, nunca vendido
    elif n_compra > 0 and n_venta == 0:
        last_purchase = group.loc[group['TIPO_TRANSACCION']=='COMPRA','FECHA'].max()
        days_since    = (TODAY - last_purchase).days
        avg_days = max_days = min_days = days_since
        ops = 0
        obs = 'solo compras (sin venta)'

    # 3) Caso 3. Sólo ventas, sin compras
    elif n_compra == 0 and n_venta > 0:
        ventas_f = group.loc[group['TIPO_TRANSACCION']=='VENTA','FECHA'].sort_values()

        # si una sola venta, arranca desde apertura
        if len(ventas_f) == 1:
            days_from_open = (ventas_f.iloc[0] - STORE_OPEN).days
            diffs = [days_from_open]
        else:
            # varias ventas: inter-venta
            diffs = ventas_f.diff().dt.days.dropna().tolist()

        # si stock > 0, agrego días desde última venta hasta hoy
        if stock > 0:
            last_sale = ventas_f.max()
            diffs.append((TODAY - last_sale).days)

        # calcular estadísticas
        avg_days = np.mean(diffs)
        max_days = np.max(diffs)
        min_days = np.min(diffs)
        ops      = len(diffs)
        obs = 'venta única desde apertura' if len(ventas_f)==1 else 'venta->venta inicial múltiple'

    # 4) Caso borde (sin transacciones)
    else:
        avg_days = max_days = min_days = np.nan
        ops = 0
        obs = 'sin transacciones'

    results.append({
        'CODIGO':               codigo,
        'PROMEDIO_DIAS_VENTAS': avg_days,
        'MAXIMO_DIAS_VENTAS':   max_days,
        'MINIMO_DIAS_VENTAS':   min_days,
        'OPERACIONES':          ops,
        'OBSERVACIONES':        obs,
        'STOCK':                stock
    })

# Convertir a DataFrame para análisis final
tiempo_promedio_ventas = pd.DataFrame(results)

In [22]:
# 5.1. PRODUCTOS que NO fueron tomados en cuenta en el flujo de trabajo anterior 
# Son 36 productos que fueron facturados antes de ingresar factura de compra. Se realizo esto, para procesar ventas anticipadas.
# Se facturo primero y luego se ingreso la factura de compra

filtro_ventas_anticipadas = tiempo_promedio_ventas[
    (tiempo_promedio_ventas['OPERACIONES'] == 0) &
    (tiempo_promedio_ventas['PROMEDIO_DIAS_VENTAS'] == 0)
]
filtro_ventas_anticipadas.count()

CODIGO                  21
PROMEDIO_DIAS_VENTAS    21
MAXIMO_DIAS_VENTAS      21
MINIMO_DIAS_VENTAS      21
OPERACIONES             21
OBSERVACIONES           21
STOCK                   21
dtype: int64

In [23]:
tiempo_promedio_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5881 entries, 0 to 5880
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CODIGO                5881 non-null   object
 1   PROMEDIO_DIAS_VENTAS  5881 non-null   float64
 2   MAXIMO_DIAS_VENTAS    5881 non-null   float64
 3   MINIMO_DIAS_VENTAS    5881 non-null   float64
 4   OPERACIONES           5881 non-null   int64
 5   OBSERVACIONES         5881 non-null   object
 6   STOCK                 5881 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 321.7+ KB

# 2.1.1. Variable Tiempo Promedio por Producto

In [24]:
compras[compras.CODIGO == "5800"]

,CODIGO,FECHA,PROVEEDOR,TIPO,CANTIDAD,PRODUCTO,COSTO_TOTAL_SIN_IVA,COSTO_UNITARIO_SIN_IVA,CATEGORIA
7701,5800,2024-11-27 08:27:00,FERREMUNDO S A-FERREMUNDO S.A.,Mercaderia,6.0,PINTURA SPRAY NEGRO BRILLANTE #39 SOL COLOR,7.92,1.32,ACCESORIO

In [25]:
# 1. Creamos variable TIEMPO PROMEDIO DE VENTAS
#Definimos los límites de los rangos y sus etiquetas
intervalos_tiempo  = [0, 60, 120, 180, np.inf]
labels = ['Estrella', 'Optimo', 'Tomar Acción', 'Tomar Acción Urgente']

# 2. Creamos el variable de acuerdo a los intervalos establecidos
tiempo_promedio_ventas['TIEMPO_PROMEDIO_VENTAS'] = pd.cut(
    tiempo_promedio_ventas['PROMEDIO_DIAS_VENTAS'],
    bins=intervalos_tiempo,
    labels=labels,
    right=True,       # el límite superior está incluido en cada bin
    include_lowest=True
)
tiempo_promedio_ventas

# 3. Agregamos 'CATEGORIA' y "PRODUCTO" a tiempo_promedio_ventas:
# Creamos dos Series indexadas por CODIGO para CATEGORIA y PRODUCTO
map_compras_cat  = compras.groupby('CODIGO')['CATEGORIA'].first()
map_ventas_cat   = ventas_limpio.groupby('CODIGO') ['CATEGORIA'].first()

map_compras_prod = compras.groupby('CODIGO')['PRODUCTO'].first()
map_ventas_prod  = ventas_limpio.groupby('CODIGO')['PRODUCTO'].first()

# Asignamos directamente CATEGORIA desde compras y ventas a tiempo_promedio_ventas
tiempo_promedio_ventas['CATEGORIA'] = (
    # Primero, intentamos con compras
    tiempo_promedio_ventas['CODIGO'].map(map_compras_cat)
    # Si sigue NaN, lo completamos con ventas
    .fillna(tiempo_promedio_ventas['CODIGO'].map(map_ventas_cat))
)

# Asignamos directamente PRODUCTO desde compras y ventas a tiempo_promedio_ventas
tiempo_promedio_ventas['PRODUCTO'] = (
    # Primero, intentamos con compras
    tiempo_promedio_ventas['CODIGO'].map(map_compras_prod)
    # Si sigue NaN, lo completamos con ventas
    .fillna(tiempo_promedio_ventas['CODIGO'].map(map_ventas_prod))
)

# 4. Creamos la categoria COMERCIO
tiempo_promedio_ventas['COMERCIO'] = tiempo_promedio_ventas['CATEGORIA'].map({
    'MAQUINARIA': 'ALMACEN',
    'ACCESORIO': 'ALMACEN',
    'REPUESTO': 'TALLER',
    'SERVICIO': 'TALLER'
    #'NO ESPECIFICA EN REPORTE COMPRAS': 'SIN COMERCIO'
})

# 5. Eliminamos los valores nulos que corresponden a productos SIN CATEGORIA. Son productos como BANDEROLAS, SEGURO TRANSPORTE, EXHIBIDOR, etc
tiempo_promedio_ventas.dropna(inplace=True)

tiempo_promedio_ventas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5876 entries, 0 to 5880
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CODIGO                  5876 non-null   object
 1   PROMEDIO_DIAS_VENTAS    5876 non-null   float64
 2   MAXIMO_DIAS_VENTAS      5876 non-null   float64
 3   MINIMO_DIAS_VENTAS      5876 non-null   float64
 4   OPERACIONES             5876 non-null   int64
 5   OBSERVACIONES           5876 non-null   object
 6   STOCK                   5876 non-null   float64
 7   TIEMPO_PROMEDIO_VENTAS  5876 non-null   category
 8   CATEGORIA               5876 non-null   object
 9   PRODUCTO                5876 non-null   object
 10  COMERCIO                5876 non-null   object
dtypes: category(1), float64(4), int64(1), object(5)
memory usage: 510.9+ KB

# Incluir aspecto dinamico
1. Calcular un STOCK_PYTHON. Este es un stock calculado a partir de las COMPRAS y VENTAS de cada producto
2. Si y solo si tiene aun stock el producto, tomar en cuenta el tiempo desde la ultima venta, hasta la fecha de hoy. Con esto agregamos la componente dinamica dentro del analisis
3. Tambien se podria incluir directamente el stock desde INVENTARIO hacia el df TIEMPO_PROMEDIO_ALMACEN

In [26]:
inventario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6371 entries, 0 to 6370
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CODIGO     6371 non-null   object
 1   PRODUCTO   6371 non-null   object
 2   MARCA      6371 non-null   object
 3   STOCK      6371 non-null   float64
 4   COSTO      6371 non-null   float64
 5   TOTAL      6371 non-null   float64
 6   PVP        6371 non-null   float64
 7   CATEGORIA  6371 non-null   object
dtypes: float64(4), object(4)
memory usage: 398.3+ KB

# Documentacion

1. **compra->venta y venta->venta**: En este caso hay varias compras y ventas, y solo cuenta el tiempo de ventas SOLO si sigue la secuencia COMPRA-VENTA y VENTA-VENTA. Nunca contabiliza la diferencia entre fechas cuando sea VENTA-COMPRA ni tampoco COMPRA-COMPRA.
2. **solo compras (sin venta)**: Estos son productos que se han comprado y nunca se han vendido. Se toma el tiempo de venta como el tiempo que sigue en stock desde que se compro hasta la fecha actual
3. **venta única desde apertura**: Productos que no han tenido ninguna compra pero muestran que han tenido una sola venta. Se puede interpretar como productos que solo se vendieron una vez (desde el inventario inicial) y se decidio no comprar mas ese producto. Se calculo como la diferencia entre la fecha de apertura y la fecha de esa unica venta.
4. **venta->venta inicial múltiple**: Productos que no reflejen ninguna Compra solo reflejan ventas.


IMPORTANTE: Dentro de este analisis no se incluyen 36 productos que se han comprado bajo pedido, en donde primero se realizo la factura de venta y luego se ha ingresado la factura de compra al sistema. CORREGIR para NO volver a realizar esto. Primero se debe ingresar la factura de compra y luego realizar la factura de venta. Caso contrario no proceder por ningun motivo. Esto crea un conflicto ya que en el sistema se esatria vendiendo un producto sin que haya ingresado como compra. (NO REALIZAR INGRESOS MANUAL DE PRODUCTO PARA REALIZAR UNA VENTA BAJO PEDIDO O VENTA ANTICIPADA).

Para reconocer estos 36 productos realizamos un filtro cuando OPERACIONES, PROMEDIO_DIAS_VENTAS, MAXIMO_DIAS_VENTAS y MINIMO_DIAS_VENTAS tienen un valor de 0

# 2.2 UTILIDAD NETA

In [27]:
# 1. Calcular MARGEN BRUTO. Ahora realizamos el analisis por producto, es decir, sumar todos los ingresos y costos variables por producto 
    # para obtener resultados a nivel de producto individual

# En lugar de tomar la variable COSTO_PROMEDIO del df compras, voy a utilizar la variable COSTO del df ventas
# Recordar que: ventas_limpio['COSTO_TOTAL_UNITARIO'] = ventas_limpio.COSTO * ventas_limpio.CANTIDAD
# Recordar que: ventas_limpio['INGRESO_TOTAL_SIN_IVA'] = ventas_limpio.V_UNITARIO * ventas_limpio.CANTIDAD

# Agrupamos por producto (CODIGO)
margen_bruto = ventas_limpio.groupby('CODIGO').agg(
    ingresos_totales            = ('INGRESO_TOTAL_SIN_IVA', 'sum'),
    costo_variable_total        = ('COSTO_TOTAL_UNITARIO', 'sum'),
    unidades_vendidas_totales   = ('CANTIDAD', 'sum')
).reset_index()

# Calculamos el margen bruto
margen_bruto['margen_bruto'] = margen_bruto['ingresos_totales'] - margen_bruto['costo_variable_total']

# Calculamos el margen bruto porcentual
margen_bruto['margen_bruto_%'] = ((margen_bruto.ingresos_totales - margen_bruto.costo_variable_total) / margen_bruto.ingresos_totales) * 100

# 2. Asignar COSTOS FIJOS TOTALES a cada producto 

# a. Definimos el costo fijo total de la empresa
COSTOS_FIJOS = 5000*12*5 # Modificar para que sea mensual y lo calcule automaticamente del historico. Compras y Ventas.
# Dependiendo del intervalo desde compra a venta o venta a venta o compra a fecha de hoy para stock>0 asignar o alocar los costos fijos producto por producto

# b. Calculamos los ingresos totales de la empresa
ingresos_totales_empresa = margen_bruto['ingresos_totales'].sum()

# c. Calculamos el porcentaje de participacion por producto
margen_bruto['%_ingresos'] = margen_bruto['ingresos_totales'] / ingresos_totales_empresa

# d. Asignamos el valor en dolares a cada producto, segun el porcentaje de ingresos de los costos fijos 
margen_bruto['costos_fijos_asignados'] = (
    margen_bruto['%_ingresos'] * COSTOS_FIJOS
)

# e. Calculamos el beneficio neto restando esos costos fijos del margen bruto
margen_bruto['beneficio_neto'] = (
    margen_bruto['margen_bruto'] - margen_bruto['costos_fijos_asignados']
)

# 3. Calculamos el beneficio promedio por producto.
margen_bruto['beneficio_promedio_por_producto'] = margen_bruto['beneficio_neto'] / margen_bruto['unidades_vendidas_totales']

# 4. Creamos una variable discreta del beneficio promedio por producto
# Definimos los puntos de corte y sus etiquetas
bins   = [-np.inf,  0,   10,   100, np.inf]
labels = ['Perdida', 'Beneficio Bajo', 'Beneficio Medio', 'Beneficio Alto']

# Creamos la nueva columna con los cortes
margen_bruto['metrica_margen_bruto'] = pd.cut(
    margen_bruto['beneficio_promedio_por_producto'],
    bins=bins,
    labels=labels,
    right=False,        # intervalos tipo [a, b)
    include_lowest=True # incluye -inf en el primer bin
)

# 5. Quiero agregar 'CATEGORIA' a margen_bruto:
for var in ['PRODUCTO', 'CATEGORIA', 'COMERCIO', 'COSTO']:
    margen_bruto = agregar_variable(
        df_origen=ventas_limpio,
        df_destino=margen_bruto,
        nombre_variable=var
    )

# 6. Agrego STOCK a margen bruto
margen_bruto = agregar_variable(
    df_origen = inventario,
    df_destino = margen_bruto,
    nombre_variable='STOCK'
)

In [28]:
margen_bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4781 entries, 0 to 4780
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CODIGO                           4781 non-null   object
 1   ingresos_totales                 4781 non-null   float64
 2   costo_variable_total             4781 non-null   float64
 3   unidades_vendidas_totales        4781 non-null   float64
 4   margen_bruto                     4781 non-null   float64
 5   margen_bruto_%                   4781 non-null   float64
 6   %_ingresos                       4781 non-null   float64
 7   costos_fijos_asignados           4781 non-null   float64
 8   beneficio_neto                   4781 non-null   float64
 9   beneficio_promedio_por_producto  4781 non-null   float64
 10  metrica_margen_bruto             4781 non-null   category
 11  PRODUCTO                         4781 non-null   object
 12  CATEGORIA                        4781 non-null   object
 13  COMERCIO                         4781 non-null   object
 14  COSTO                            4781 non-null   float64
 15  STOCK                            4773 non-null   float64
dtypes: category(1), float64(11), object(4)
memory usage: 565.3+ KB

# 2.2.1. UTILIDAD NETA real tomando en cuenta COSTOS reales en el tiempo

In [29]:
# Parámetros
STORE_OPEN = pd.Timestamp('2020-10-01')
TODAY      = FECHA_CORTE_DATOS   # fecha de los datos, NO la de ejecucion

# 1) Cargar y preparar datos
combined_df      = combined_df.copy()
ventas_limpio    = ventas_limpio.copy()
inventario      = inventario.copy()
# Cargar costos fijos mensuales para ser leido por parquet
costos_path = RAW / "costos_fijos_historico.xlsx"

if costos_path.exists():
    costos_fijos_raw = pd.read_excel(costos_path, sheet_name=0, engine="openpyxl")
else:
    # DataFrame vacío con columnas esperadas; ajusta nombres si los tuyos difieren
    costos_fijos_raw = pd.DataFrame(columns=["FECHA", "ALMACEN", "TALLER"])
    print("⚠️ No se encontró 'costos_fijos_historico.xlsx'. Se continúa con DF vacío.")

# Preparar costos fijos mensuales
costos_fijos_raw['FECHA'] = pd.to_datetime(costos_fijos_raw['FECHA'])
costos_fijos_raw['MES']   = costos_fijos_raw['FECHA'].dt.to_period('M')
monthly_costs = (
    costos_fijos_raw
    .groupby('MES', as_index=True)[['ALMACEN','TALLER']]
    .sum()
    .sort_index()
)

if monthly_costs.empty:
    raise ValueError(
        "costos_fijos_historico.xlsx no tiene filas utilizables. "
        "Se esperan las columnas FECHA, ALMACEN y TALLER."
    )

# El excel de costos puede no cubrir todos los meses del historico. En vez de
# reventar con un KeyError a mitad del bucle, se completa el rango: hacia atras
# con el primer valor conocido y hacia adelante con el ultimo.
_mes_min = min(monthly_costs.index.min(), combined_df['FECHA'].min().to_period('M'))
_mes_max = max(monthly_costs.index.max(), FECHA_CORTE_DATOS.to_period('M'))
_rango_completo = pd.period_range(_mes_min, _mes_max, freq='M')

_faltantes = [m for m in _rango_completo if m not in monthly_costs.index]
monthly_costs = monthly_costs.reindex(_rango_completo).ffill().bfill()

if _faltantes:
    print(
        f"AVISO: costos_fijos_historico.xlsx no cubre {len(_faltantes)} mes(es) "
        f"({_faltantes[0]} .. {_faltantes[-1]}). Se completaron con el valor mas "
        "cercano conocido. Actualiza el archivo para que el reparto sea exacto."
    )

# Mapeo de stock por producto
stock_map = inventario.set_index('CODIGO')['STOCK'].to_dict()

# Asegurar datetime en los DataFrames clave
combined_df['FECHA']    = pd.to_datetime(combined_df['FECHA'])
ventas_limpio['FECHA']  = pd.to_datetime(ventas_limpio['FECHA'])

results = []

# 2) Bucle por producto
for codigo, group in combined_df.groupby('CODIGO'):
    grp = group.sort_values('FECHA').reset_index(drop=True)
    n_compra = (grp['TIPO_TRANSACCION']=='COMPRA').sum()
    n_venta  = (grp['TIPO_TRANSACCION']=='VENTA').sum()
    stock    = stock_map.get(codigo, 0)

    # Si nunca se vendió, no tiene beneficio neto
    if n_venta == 0:
        results.append({
            'CODIGO':                           codigo,
            'costos_fijos_asignados':           np.nan,
            'beneficio_neto':                   np.nan,
            'beneficio_promedio_por_producto':  np.nan
        })
        continue

    # 2.1) Determinar intervalo de exposición
    if n_compra > 0:
        start_date = grp.loc[grp['CODIGO'] == codigo,'FECHA'].min()
    else:
        start_date = STORE_OPEN

    if stock > 0:
        end_date = TODAY
    else:
        end_date = grp.loc[grp["CODIGO"] == codigo,'FECHA'].max()

    # 2.2) Meses completos en el intervalo
    start_mes = start_date.to_period('M')
    end_mes   = end_date.to_period('M')
    meses_intervalo = pd.period_range(start_mes, end_mes, freq='M')

    # 2.3) Ventas e ingresos en el intervalo
    mask_prod = (
        (ventas_limpio['CODIGO']==codigo) &
        (ventas_limpio['FECHA']>=start_date) &
        (ventas_limpio['FECHA']<=end_date)
    )
    df_p = ventas_limpio.loc[mask_prod]
    ingresos_prod  = df_p['INGRESO_TOTAL_SIN_IVA'].sum()
    unidades_prod  = df_p['CANTIDAD'].sum()
    costo_var_prod = df_p['COSTO_TOTAL_UNITARIO'].sum()

    # 2.4) Margen bruto del producto
    margen_bruto_prod = ingresos_prod - costo_var_prod

    # 2.4.1) Margen bruto en %
    margen_bruto_pct = (margen_bruto_prod / ingresos_prod) if ingresos_prod > 0 else np.nan

    # 2.5) Ingresos de la empresa en meses completos del intervalo
    ingresos_emp = (
        ventas_limpio
        .loc[ventas_limpio['FECHA'].dt.to_period('M').isin(meses_intervalo),
             'INGRESO_TOTAL_SIN_IVA']
        .sum()
    )
    
    # Se anade las ventas aproximadas de la empresa durante el periodo 2021-09 a 2020-09 para aquellos productos
    # que tienen ventas y no tienen compras registradas, por lo tanto se asume que han estado desde la apertura 
    if n_compra == 0:
        ingresos_emp += 216000
    
    pct_ingresos = ingresos_prod / ingresos_emp if ingresos_emp>0 else 0

    # 2.6) Sumar costos fijos del intervalo según ALMACEN/TALLER
    comercio = ventas_limpio.loc[ventas_limpio['CODIGO']==codigo,'COMERCIO'].iloc[0]
    cf_total = monthly_costs.reindex(meses_intervalo)[comercio].sum()

    # 2.7) Costos fijos asignados
    costos_fijos_asignados = pct_ingresos * cf_total

    # 2.8) Beneficio neto y beneficio neto por unidad
    beneficio_neto = margen_bruto_prod - costos_fijos_asignados
    beneficio_unit = beneficio_neto / unidades_prod if unidades_prod>0 else np.nan

    # 2.9) Guardar resultados
    results.append({
        'CODIGO':                           codigo,
        'start_date':                       start_date,
        'end_date':                         end_date,
        'meses_intervalo':                  meses_intervalo.tolist(),
        'ingresos_prod_intervalo':          ingresos_prod,
        'unidades_vendidas_totales':        unidades_prod,
        'costo_variable_total':             costo_var_prod,
        'margen_bruto':                     margen_bruto_prod,
        'margen_bruto_%':                   margen_bruto_pct,
        'ingresos_emp_intervalo':           ingresos_emp,
        '%_ingresos':                       pct_ingresos,
        'costos_fijos_intervalo':           cf_total,
        'costos_fijos_asignados':           costos_fijos_asignados,
        'beneficio_neto':                   beneficio_neto,
        'beneficio_promedio_por_producto':  beneficio_unit
    })

# 3) DataFrame final
margen_bruto_real = pd.DataFrame(results)

# Convertir margen_bruto_% a porcentaje para el Dashboard
margen_bruto_real['margen_bruto_%'] = margen_bruto_real['margen_bruto_%'] * 100

# 4. Creamos una variable discreta del beneficio promedio por producto
# Definimos los puntos de corte y sus etiquetas
bins   = [-np.inf,  0,   10,   100, np.inf]
labels = ['Perdida', 'Beneficio Bajo', 'Beneficio Medio', 'Beneficio Alto']

# Creamos la nueva columna con los cortes
margen_bruto_real['metrica_margen_bruto'] = pd.cut(
    margen_bruto_real['beneficio_promedio_por_producto'],
    bins=bins,
    labels=labels,
    right=False,        # intervalos tipo [a, b)
    include_lowest=True # incluye -inf en el primer bin
)

# 5. Quiero agregar 'CATEGORIA' a margen_bruto:
for var in ['PRODUCTO', 'CATEGORIA', 'COMERCIO', 'COSTO']:
    margen_bruto_real = agregar_variable(
        df_origen=ventas_limpio,
        df_destino=margen_bruto_real,
        nombre_variable=var
    )

# 6. Agrego STOCK a margen bruto
margen_bruto_real = agregar_variable(
    df_origen = inventario,
    df_destino = margen_bruto_real,
    nombre_variable='STOCK'
)

# 7. Eliminamos los valores nulos que corresponden a productos SIN VENTAS que solo han tenido compras
# Mantenemos los productos que no aparecen en inventario como SERVICIOS y otros con el subset
margen_bruto_real.dropna(subset=['beneficio_promedio_por_producto'], inplace=True)

In [30]:
# Estos productos correponden a los items que solo tienen COMPRAS y NINGUNA VENTA por eso no se puede calcular el MARGEN BRUTO.
# Para estos casos, asignar margen bruto nan. Luego como se pueden integrar esos valores nan dentro del dashboard para que calule promedios, etc.
# Buscar si hay alguna forma de ignorar los nanM PERO ESTO YA ES EN PRODUCCION. Hasta aqui debemos tener listo el excel completo con todos los productos
# existentes con inventario incluyendo los 95 que no constan ni en COMPRAS ni VENTAS. DEBERIAN SER 2836 PRODUCTOS con stock>0 MENOS los 95 productos
# que no estan en el reporte de compras ni en el reporte de ventas + los productos con stock 0 que se ingresen dentro del dashoboard


# ES IMPORTANTE CONTAR EN EL DASHBOARD CON TODOS LOS PRODUCTOS INCLUYENDO LOS DE STOCK = 0 PORQUE SE DEBE TAMBIEN ANALIZAR ESOS PRODUCTOS
# QUE SE HAN ACABADO O QUE QUIZAS SE VENDIERON BIEN Y SE DEJARON DE TRAER

# SOLO EN LA TABLA DEL DASHBOARD MOSTRAR LOS PRODUCTOS CON STOCK>0. SE PUEDE ANADIR BOTON PARA DESCARGAR PRODUTOS CON BUENA ROTACION Y VERIFICAR 
# QUE TIENEN STOCK 0 PARA PEDIR

# DOCUMENTACION 

En este apartado se realizó el calculo de 4 principales variables o indicadores:

1. **Margen Bruto** o utilidad bruto para cada producto (Ingreso_total_historico - costo_producto_total_historico)
2. **Distribucion de  COSTOS FIJOS** en cada producto (De acuerdo al ingreso total de cada producto. Productos que han generado mayor ingreso, se asigna un costo fijo mayor a ese producto)
3. **Beneficio Neto**. Es el beneficio total que ha generado un producto historicamente luego de asignarle el costo fijo correspondiente
4. **Beneficio Promedio por Producto**. Es el beneficio en promedio por cada unidad vendida


Variables del DF:
- **margen_bruto**: También llamado margen de contribución total del producto, representa cuánto dinero aportan las ventas de ese producto para cubrir costos fijos y generar ganancias, en conjunto. Es la suma de los márgenes de contribución de todas sus unidades vendidas.
- **ingresos_totales**: suma de los ingresos de todas las transacciones de ese producto SIN IVA.
- **costo_variable_total**: suma de todos los costos variables (costo unitario * cantidad) SIN IVA de las ventas de ese producto.
- **unidades_vendidas_totales**: suma de las cantidades vendidas del producto (esto también puede obtenerse del mismo agrupamiento).

# **** DASHBOARD ****

Se va a unir los analisis de TIEMPO PROMEDIO y UTILIDAD BRUTA para obtener un unico DF que va a ser utilizado como fuente de informacion para el dashboard

In [31]:
margen_bruto_real.info(), margen_bruto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4781 entries, 0 to 5880
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CODIGO                           4781 non-null   object
 1   start_date                       4781 non-null   datetime64[ns]
 2   end_date                         4781 non-null   datetime64[ns]
 3   meses_intervalo                  4781 non-null   object
 4   ingresos_prod_intervalo          4781 non-null   float64
 5   unidades_vendidas_totales        4781 non-null   float64
 6   costo_variable_total             4781 non-null   float64
 7   margen_bruto                     4781 non-null   float64
 8   margen_bruto_%                   4781 non-null   float64
 9   ingresos_emp_intervalo           4781 non-null   float64
 10  %_ingresos                       4781 non-null   float64
 11  costos_fijos_intervalo           4781 non-null   float64
 12  costos_fijos_asignados           4781 non-null   float64
 13  beneficio_neto                   4781 non-null   float64
 14  beneficio_promedio_por_producto  4781 non-null   float64
 15  metrica_margen_bruto             4781 non-null   category
 16  PRODUCTO                         4781 non-null   object
 17  CATEGORIA                        4781 non-null   object
 18  COMERCIO                         4781 non-null   object
 19  COSTO                            4781 non-null   float64
 20  STOCK                            4773 non-null   float64
dtypes: category(1), datetime64[ns](2), float64(13), object(5)
memory usage: 789.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4781 entries, 0 to 4780
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CODIGO                           4781 non-null   object
 1   ingresos_totales                 4781 non-null   float64
 2   costo_variable_total             4781 non-null   float64
 3   unidades_vendidas_totales        4781 non-null   float64
 4   margen_bruto                     4781 non-null   float64
 5   margen_bruto_%                   4781 non-null   float64
 6   %_ingresos                       4781 non-null   float64
 7   costos_fijos_asignados           4781 non-null   float64
 8   beneficio_neto                   4781 non-null   float64
 9   beneficio_promedio_por_producto  4781 non-null   float64
 10  metrica_margen_bruto             4781 non-null   category
 11  PRODUCTO                         4781 non-null   object
 12  CATEGORIA                        4781 non-null   object
 13  COMERCIO                         4781 non-null   object
 14  COSTO                            4781 non-null   float64
 15  STOCK                            4773 non-null   float64
dtypes: category(1), float64(11), object(4)
memory usage: 565.3+ KB

(None, None)

## 2.3. DIAGNOSTICO DEL LIBRO Y RECONSTRUCCION DE LA APERTURA

In [ ]:
"""
Diagnostico de calidad del libro de movimientos y estimacion de la apertura.

Contexto (confirmado con el negocio): el inventario inicial nunca se cargo como
compras, hubo una migracion a otro software que dejo productos sin corregir, y
existen ingresos manuales y ventas anticipadas que no pasaron por compras. Por eso
el stock acumulado se va a negativo en parte del catalogo. No hay un corte de
inventario de 2021 disponible, asi que la apertura se ESTIMA.

Criterio: la apertura de un producto es la cantidad que hace que el libro cierre
en el stock que hoy reporta el inventario.

    desfase            = STOCK_HOY - neto_movimientos
    STOCK_APERTURA_EST = max(0,  desfase)   -> faltan entradas al inicio
    AJUSTE_SALIDA      = max(0, -desfase)   -> sobran entradas: hay salidas no registradas

Si tras aplicar la apertura el acumulado sigue bajando de cero, el hueco no esta
solo al inicio sino a mitad de la historia: eso se marca como NEGATIVO_RESIDUAL y
los dias de ese producto no son confiables.

Nada de esto se aplica a las categorias no inventariables (servicios).
"""

# Categorias que no llevan stock: no se les reconstruye nada.
# Ampliar esta lista si aparecen otros items no inventariables mal categorizados.
CATEGORIAS_NO_INVENTARIABLES = {"SERVICIO"}

# Margen para leer una venta previa a la compra como desfase de facturacion
# y no como inventario de apertura.
DIAS_VENTA_ANTICIPADA = 30

_mov = combined_df.copy()
_mov["FECHA"]  = pd.to_datetime(_mov["FECHA"])
_mov["CODIGO"] = _mov["CODIGO"].astype(str).str.strip()
_mov["TIPO_TRANSACCION"] = _mov["TIPO_TRANSACCION"].astype(str).str.strip().str.upper()
_mov = _mov[_mov["TIPO_TRANSACCION"].isin(["COMPRA", "VENTA"])].copy()
_mov["CANTIDAD"] = pd.to_numeric(_mov["CANTIDAD"], errors="coerce").abs()
_mov["SIGNO"] = _mov["CANTIDAD"] * _mov["TIPO_TRANSACCION"].map({"COMPRA": 1, "VENTA": -1})
_mov = _mov.sort_values(["CODIGO", "FECHA"])
_mov["ACUM"] = _mov.groupby("CODIGO")["SIGNO"].cumsum()

_es_compra = _mov["TIPO_TRANSACCION"].eq("COMPRA")

diagnostico_stock = (
    _mov.assign(_C=_es_compra.astype(int), _V=(~_es_compra).astype(int))
        .groupby("CODIGO", as_index=False)
        .agg(
            NETO_MOVIMIENTOS=("SIGNO", "sum"),
            MIN_ACUMULADO=("ACUM", "min"),
            PRIMERA_FECHA=("FECHA", "min"),
            ULTIMA_FECHA=("FECHA", "max"),
            N_COMPRAS=("_C", "sum"),
            N_VENTAS=("_V", "sum"),
        )
)

# --- Stock que hoy reporta el inventario ---
_inv = inventario.copy()
_inv["CODIGO"] = _inv["CODIGO"].astype(str).str.strip()
_stock_hoy = _inv.groupby("CODIGO")["STOCK"].first()
diagnostico_stock["STOCK_HOY"] = diagnostico_stock["CODIGO"].map(_stock_hoy).fillna(0.0)

# --- Categoria, para excluir lo no inventariable ---
_cat = pd.concat([
    compras[["CODIGO", "CATEGORIA"]],
    ventas_limpio[["CODIGO", "CATEGORIA"]],
], ignore_index=True)
_cat["CODIGO"] = _cat["CODIGO"].astype(str).str.strip()
_cat = _cat.groupby("CODIGO")["CATEGORIA"].first()
diagnostico_stock["NO_INVENTARIABLE"] = (
    diagnostico_stock["CODIGO"].map(_cat).isin(CATEGORIAS_NO_INVENTARIABLES)
)

# --- Estimacion de la apertura y del ajuste de salida ---
_desfase = diagnostico_stock["STOCK_HOY"] - diagnostico_stock["NETO_MOVIMIENTOS"]
diagnostico_stock["STOCK_APERTURA_EST"] = _desfase.clip(lower=0)
diagnostico_stock["AJUSTE_SALIDA"]      = (-_desfase).clip(lower=0)

_no_inv = diagnostico_stock["NO_INVENTARIABLE"]
diagnostico_stock.loc[_no_inv, ["STOCK_APERTURA_EST", "AJUSTE_SALIDA"]] = 0.0

# --- Banderas ---
diagnostico_stock["NEGATIVO_RESIDUAL"] = (
    (diagnostico_stock["STOCK_APERTURA_EST"] + diagnostico_stock["MIN_ACUMULADO"] < 0)
    & ~_no_inv
)
diagnostico_stock["SIN_COMPRAS"] = diagnostico_stock["N_COMPRAS"].eq(0)

_p_venta  = _mov.loc[~_es_compra, ["CODIGO", "FECHA"]].groupby("CODIGO")["FECHA"].min()
_p_compra = _mov.loc[_es_compra,  ["CODIGO", "FECHA"]].groupby("CODIGO")["FECHA"].min()
_dias_desfase = (
    pd.to_datetime(diagnostico_stock["CODIGO"].map(_p_compra))
    - pd.to_datetime(diagnostico_stock["CODIGO"].map(_p_venta))
).dt.days

diagnostico_stock["VENTA_ANTICIPADA"] = (
    diagnostico_stock["N_COMPRAS"].gt(0)
    & _dias_desfase.notna()
    & _dias_desfase.gt(0)
    & _dias_desfase.le(DIAS_VENTA_ANTICIPADA)
)

# --- Resumen legible: que se hizo con cada producto ---
_cond = [
    _no_inv,
    diagnostico_stock["AJUSTE_SALIDA"] > 0,
    diagnostico_stock["STOCK_APERTURA_EST"] > 0,
]
_lab = ["NO_INVENTARIABLE", "SALIDA_NO_REGISTRADA", "APERTURA_ESTIMADA"]
diagnostico_stock["CALIDAD_DATOS"] = np.select(_cond, _lab, default="OK")

print("== Diagnostico del libro de movimientos ==")
print(diagnostico_stock["CALIDAD_DATOS"].value_counts().to_string())
print()
print(f"NEGATIVO_RESIDUAL : {int(diagnostico_stock['NEGATIVO_RESIDUAL'].sum()):,}")
print(f"SIN_COMPRAS       : {int(diagnostico_stock['SIN_COMPRAS'].sum()):,}")
print(f"VENTA_ANTICIPADA  : {int(diagnostico_stock['VENTA_ANTICIPADA'].sum()):,}")
print()
print(f"Unidades inyectadas como apertura : {diagnostico_stock['STOCK_APERTURA_EST'].sum():,.0f}")
print(f"Unidades retiradas como ajuste    : {diagnostico_stock['AJUSTE_SALIDA'].sum():,.0f}")

## RESUMEN FINAL

In [32]:
# 1. UNIR ARCHIVOS Y GENERAR ARCHIVO PARA DASHBOARD
# Combinamos los df de tiempo promedio limpio y marge bruto
# Partimos de una copia para no tocar el df original
resumen_final = tiempo_promedio_ventas.copy()

for var in ['margen_bruto', 'margen_bruto_%', 'beneficio_promedio_por_producto','metrica_margen_bruto', 'COSTO', 'unidades_vendidas_totales']:
    resumen_final = agregar_variable(
        df_origen=margen_bruto,
        df_destino=resumen_final,
        nombre_variable=var
    )

# 2. CREAR SUBCATEGORIA
# Definir condiciones (cada una es booleana)
conditions = [
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('TALADRO',    case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('SOLDADORA', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('HIDROLAVADORA', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('AMOLADORA', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('ROTOMARTILLO', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('LLAVE DE IMPACTO', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('COMPRESOR', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('DEMOLEDOR', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('GAT', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('BOMBA', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('MOTOSIERRA', case=False, na=False)),
    (resumen_final['CATEGORIA'] == 'MAQUINARIA') & (resumen_final['PRODUCTO'].str.contains('GENERADOR', case=False, na=False))
    
]

# Definir las subcategorías que se asignan según cada condición
choices = ['TALADROS', 'SOLDADORAS', 'HIDROLAVADORAS', 'AMOLADORAS', 'ROTOMARTILLOS', 'LLAVES DE IMPACTO', 'COMPRESORES', 'DEMOLEDORES', 'GATOS HIDRAULICOS', 'BOMBAS DE AGUA', 'MOTOSIERRAS', 'GENERADORES']

# Crear la nueva columna con np.select
resumen_final['SUBCATEGORIA'] = np.select(conditions, choices, default='NO TIENE SUBCATEGORIA')

# 3. AGREGAMOS LA VARIABLE "MARCA" y "STOCK":
for var in ['MARCA', 'STOCK']:
    resumen_final = agregar_variable(
        df_origen=inventario,
        df_destino=resumen_final,
        nombre_variable=var
    )

# 4. COLOCAR STOCK=0 a PRODUCTOS PROBLEMA con STOCK NaN. Son productos como SERVICIO que no aparecen en inventario (Si deberia aparecer asi sea con inventario 0)
# Mejor se decide a colocar marca RESTAURADORES a aquellos items que tienen MARCA NaN que coincide con los items que tienen STOCK NaN, ya que estos
# productos vienen desde el reporte de inventario
resumen_final['MARCA'] = resumen_final['MARCA'].fillna('RESTAURADORES')

# 4. EXPORTAR ARCHIVO
#resumen_final.to_excel('Data_Dashboard.xlsx', index = False)

In [33]:
resumen_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5876 entries, 0 to 5880
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CODIGO                           5876 non-null   object
 1   PROMEDIO_DIAS_VENTAS             5876 non-null   float64
 2   MAXIMO_DIAS_VENTAS               5876 non-null   float64
 3   MINIMO_DIAS_VENTAS               5876 non-null   float64
 4   OPERACIONES                      5876 non-null   int64
 5   OBSERVACIONES                    5876 non-null   object
 6   STOCK                            5868 non-null   float64
 7   TIEMPO_PROMEDIO_VENTAS           5876 non-null   category
 8   CATEGORIA                        5876 non-null   object
 9   PRODUCTO                         5876 non-null   object
 10  COMERCIO                         5876 non-null   object
 11  margen_bruto                     4781 non-null   float64
 12  margen_bruto_%                   4781 non-null   float64
 13  beneficio_promedio_por_producto  4781 non-null   float64
 14  metrica_margen_bruto             4781 non-null   category
 15  COSTO                            4781 non-null   float64
 16  unidades_vendidas_totales        4781 non-null   float64
 17  SUBCATEGORIA                     5876 non-null   object
 18  MARCA                            5876 non-null   object
dtypes: category(2), float64(9), int64(1), object(7)
memory usage: 838.2+ KB

## RESUMEN FINAL REAL

Tomando en cuenta la utilidad neta real

In [34]:
# 1. UNIR ARCHIVOS Y GENERAR ARCHIVO PARA DASHBOARD
# Combinamos los df de tiempo promedio limpio y marge bruto
# Partimos de una copia para no tocar el df original
resumen_final_real = tiempo_promedio_ventas.copy()

for var in ['margen_bruto', 'margen_bruto_%', 'beneficio_promedio_por_producto','metrica_margen_bruto', 'COSTO', 'unidades_vendidas_totales']:
    resumen_final_real = agregar_variable(
        df_origen=margen_bruto_real,
        df_destino=resumen_final_real,
        nombre_variable=var
    )

# 2. CREAR SUBCATEGORIA
# Definir condiciones (cada una es booleana)
conditions = [
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('TALADRO',    case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('SOLDADORA', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('HIDROLAVADORA', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('AMOLADORA', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('ROTOMARTILLO', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('LLAVE DE IMPACTO', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('COMPRESOR', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('DEMOLEDOR', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('GAT', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('BOMBA', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('MOTOSIERRA', case=False, na=False)),
    (resumen_final_real['CATEGORIA'] == 'MAQUINARIA') & (resumen_final_real['PRODUCTO'].str.contains('GENERADOR', case=False, na=False))
    
]

# Definir las subcategorías que se asignan según cada condición
choices = ['TALADROS', 'SOLDADORAS', 'HIDROLAVADORAS', 'AMOLADORAS', 'ROTOMARTILLOS', 'LLAVES DE IMPACTO', 'COMPRESORES', 'DEMOLEDORES', 'GATOS HIDRAULICOS', 'BOMBAS DE AGUA', 'MOTOSIERRAS', 'GENERADORES']

# Crear la nueva columna con np.select
resumen_final_real['SUBCATEGORIA'] = np.select(conditions, choices, default='NO TIENE SUBCATEGORIA')

# 3. AGREGAMOS LA VARIABLE "MARCA" y "STOCK":
for var in ['MARCA', 'STOCK']:
    resumen_final_real = agregar_variable(
        df_origen=inventario,
        df_destino=resumen_final_real,
        nombre_variable=var
    )

# 4. COLOCAR STOCK=0 a PRODUCTOS PROBLEMA con STOCK NaN. Son productos como SERVICIO que no aparecen en inventario (Si deberia aparecer asi sea con inventario 0)
# Mejor se decide a colocar marca RESTAURADORES a aquellos items que tienen MARCA NaN que coincide con los items que tienen STOCK NaN, ya que estos
# productos vienen desde el reporte de inventario
resumen_final_real['MARCA'] = resumen_final_real['MARCA'].fillna('RESTAURADORES')

# 4. EXPORTAR ARCHIVO
#resumen_final_real.to_excel('Data_Dashboard_real.xlsx', index = False)

In [35]:
resumen_final_real.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5876 entries, 0 to 5880
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CODIGO                           5876 non-null   object
 1   PROMEDIO_DIAS_VENTAS             5876 non-null   float64
 2   MAXIMO_DIAS_VENTAS               5876 non-null   float64
 3   MINIMO_DIAS_VENTAS               5876 non-null   float64
 4   OPERACIONES                      5876 non-null   int64
 5   OBSERVACIONES                    5876 non-null   object
 6   STOCK                            5868 non-null   float64
 7   TIEMPO_PROMEDIO_VENTAS           5876 non-null   category
 8   CATEGORIA                        5876 non-null   object
 9   PRODUCTO                         5876 non-null   object
 10  COMERCIO                         5876 non-null   object
 11  margen_bruto                     4781 non-null   float64
 12  margen_bruto_%                   4781 non-null   float64
 13  beneficio_promedio_por_producto  4781 non-null   float64
 14  metrica_margen_bruto             4781 non-null   category
 15  COSTO                            4781 non-null   float64
 16  unidades_vendidas_totales        4781 non-null   float64
 17  SUBCATEGORIA                     5876 non-null   object
 18  MARCA                            5876 non-null   object
dtypes: category(2), float64(9), int64(1), object(7)
memory usage: 838.2+ KB

In [ ]:
# Incorporar las banderas de diagnostico al marco que se exporta al dashboard.
# Asi la app puede mostrar, producto por producto, que se asumio sobre su historia.
resumen_final_real["CODIGO"] = resumen_final_real["CODIGO"].astype(str).str.strip()
_diag = diagnostico_stock.copy()
_diag["CODIGO"] = _diag["CODIGO"].astype(str).str.strip()

resumen_final_real = resumen_final_real.merge(
    _diag[["CODIGO"] + COLS_DIAG], on="CODIGO", how="left"
)

# Productos que llegan del inventario pero no tienen ningun movimiento registrado
resumen_final_real["CALIDAD_DATOS"] = (
    resumen_final_real["CALIDAD_DATOS"].fillna("SIN_MOVIMIENTOS").astype("category")
)
for _c in ["STOCK_APERTURA_EST", "AJUSTE_SALIDA"]:
    resumen_final_real[_c] = resumen_final_real[_c].fillna(0.0).astype("float32")
for _c in ["NEGATIVO_RESIDUAL", "SIN_COMPRAS", "VENTA_ANTICIPADA"]:
    resumen_final_real[_c] = resumen_final_real[_c].fillna(False).astype(bool)

print(resumen_final_real["CALIDAD_DATOS"].value_counts(dropna=False).to_string())

# 4. PAGINA HEADQUARTERS (MANEJO GERENCIAL)

In [37]:
combined_df.head()

                FECHA CODIGO  CANTIDAD TIPO_TRANSACCION
0 2021-11-23 12:12:15   1000       2.0           COMPRA
1 2023-10-10 00:00:00   1000       1.0            VENTA
2 2024-03-16 00:00:00   1000       1.0            VENTA
3 2021-11-23 12:12:15   1001       2.0           COMPRA
4 2023-05-25 00:00:00   1001       1.0            VENTA

### 1. CANTIDAD_SIGNO para asignar signo a cantidad

In [38]:
# I) ASIGNAR SIGNO A LAS TRANSACCIONES DE MOVIMIENTOS
mov_combined_df = combined_df.copy()

# 1. Tipos y limpieza mínima
mov_combined_df["FECHA"]  = pd.to_datetime(mov_combined_df["FECHA"], errors="coerce")
mov_combined_df["CODIGO"] = mov_combined_df["CODIGO"].astype(str).str.strip()
mov_combined_df["CANTIDAD"] = pd.to_numeric(mov_combined_df["CANTIDAD"], errors="coerce").abs()

# 2. Por seguridad, normalizamos el texto y nos quedamos con COMPRA/VENTA
mov_combined_df["TIPO_TRANSACCION"] = mov_combined_df["TIPO_TRANSACCION"].astype(str).str.strip().str.upper()
mov_combined_df = mov_combined_df[mov_combined_df["TIPO_TRANSACCION"].isin(["COMPRA", "VENTA"])].copy()

# 3. Asignar signo: COMPRA (+), VENTA (−)
signo = {"COMPRA": 1, "VENTA": -1}
mov_combined_df["CANTIDAD_SIGNO"] = mov_combined_df["CANTIDAD"] * mov_combined_df["TIPO_TRANSACCION"].map(signo)

# 4. Filtrar solo productos con al menos una COMPRA
#codigos_con_compra = set(mov.loc[mov["TIPO_TRANSACCION"] == "COMPRA", "CODIGO"].unique())
#mov = mov[mov["CODIGO"].isin(codigos_con_compra)].copy()

# Orden cronológico por producto
mov_combined_df = mov_combined_df.sort_values(["CODIGO", "FECHA"]).reset_index(drop=True)

# 5. Stock acumulado por transacción
mov_combined_df["STOCK_ACUM"] = mov_combined_df.groupby("CODIGO")["CANTIDAD_SIGNO"].cumsum()

# 6. DataFrame listo para los siguientes pasos
mov_limpio_df = mov_combined_df[["FECHA", "CODIGO", "TIPO_TRANSACCION", "CANTIDAD_SIGNO", "STOCK_ACUM"]].copy()

# Chequeo rápido
resumen = {
    "filas_totales": len(mov_combined_df),
    "productos_unicos": mov_combined_df["CODIGO"].nunique(),
    "compras": int((mov_combined_df["TIPO_TRANSACCION"] == "COMPRA").sum()),
    "ventas": int((mov_combined_df["TIPO_TRANSACCION"] == "VENTA").sum()),
}
print(resumen)

{'filas_totales': 65839, 'productos_unicos': 5881, 'compras': 10199, 'ventas': 55640}

In [39]:
mov_limpio_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65839 entries, 0 to 65838
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FECHA             65839 non-null  datetime64[ns]
 1   CODIGO            65839 non-null  object
 2   TIPO_TRANSACCION  65839 non-null  object
 3   CANTIDAD_SIGNO    65839 non-null  float64
 4   STOCK_ACUM        65839 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 2.5+ MB

In [ ]:
"""
Aplica al libro de movimientos las capas estimadas en 'diagnostico_stock'.

  APERTURA : entra un dia antes del primer movimiento del producto.
  AJUSTE   : sale en la fecha del ultimo movimiento conocido. No se sabe cuando
             ocurrio realmente la salida, asi que se imputa al cierre; queda
             marcada como SALIDA_NO_REGISTRADA para que no se confunda con venta.

Se usan tipos propios ('APERTURA' / 'AJUSTE') y NO 'COMPRA'/'VENTA', para que el
calculo de tiempo promedio no los cuente como transacciones comerciales.
"""

_d = diagnostico_stock
_inyectar = []

_ap = _d[(_d["STOCK_APERTURA_EST"] > 0) & (~_d["NO_INVENTARIABLE"])]
if len(_ap):
    _inyectar.append(pd.DataFrame({
        "FECHA":            _ap["PRIMERA_FECHA"] - pd.Timedelta(days=1),
        "CODIGO":           _ap["CODIGO"],
        "TIPO_TRANSACCION": "APERTURA",
        "CANTIDAD_SIGNO":   _ap["STOCK_APERTURA_EST"].astype(float),
    }))

_aj = _d[(_d["AJUSTE_SALIDA"] > 0) & (~_d["NO_INVENTARIABLE"])]
if len(_aj):
    _inyectar.append(pd.DataFrame({
        "FECHA":            _aj["ULTIMA_FECHA"],
        "CODIGO":           _aj["CODIGO"],
        "TIPO_TRANSACCION": "AJUSTE",
        "CANTIDAD_SIGNO":   -_aj["AJUSTE_SALIDA"].astype(float),
    }))

_neg_antes = int((mov_limpio_df["STOCK_ACUM"] < 0).sum())

mov_limpio_df["CODIGO"] = mov_limpio_df["CODIGO"].astype(str).str.strip()

if _inyectar:
    _ajustes_df = pd.concat(_inyectar, ignore_index=True)
    _ajustes_df["CODIGO"] = _ajustes_df["CODIGO"].astype(str).str.strip()
    mov_limpio_df = pd.concat(
        [mov_limpio_df[["FECHA", "CODIGO", "TIPO_TRANSACCION", "CANTIDAD_SIGNO"]], _ajustes_df],
        ignore_index=True,
    )

# La apertura debe quedar antes que cualquier movimiento del mismo dia
_orden = {"APERTURA": 0, "COMPRA": 1, "VENTA": 2, "AJUSTE": 3}
mov_limpio_df["_ord"] = mov_limpio_df["TIPO_TRANSACCION"].map(_orden).fillna(9)
mov_limpio_df = (
    mov_limpio_df
    .sort_values(["CODIGO", "FECHA", "_ord"])
    .drop(columns="_ord")
    .reset_index(drop=True)
)
mov_limpio_df["STOCK_ACUM"] = mov_limpio_df.groupby("CODIGO")["CANTIDAD_SIGNO"].cumsum()

_neg_despues = int((mov_limpio_df["STOCK_ACUM"] < 0).sum())
print(f"Filas inyectadas          : {sum(len(x) for x in _inyectar):,}")
print(f"Movimientos con stock < 0 : {_neg_antes:,} -> {_neg_despues:,}")
print(f"Productos afectados       : {mov_limpio_df.loc[mov_limpio_df['STOCK_ACUM'] < 0, 'CODIGO'].nunique():,}")

### 3. ANTIGUEDAD FIFO Y COBERTURA MOVIL

In [ ]:
"""
Antiguedad del inventario por capas FIFO.

Se reproduce el libro de cada producto como una cola: cada entrada (APERTURA o
COMPRA) agrega una capa con su fecha, y cada salida (VENTA o AJUSTE) consume de
la capa mas antigua. De ahi salen dos medidas distintas que hoy estaban mezcladas
en un solo numero:

  DIAS_ESTANTERIA_VENDIDO : cuanto estuvo en tienda lo que YA se vendio.
                            Historia cerrada, ponderada por unidad.
  ANTIGUEDAD_STOCK_DIAS   : cuanto lleva parado lo que TODAVIA esta en bodega.
                            No tiene censura: la edad a la fecha de corte se conoce.

Solo las VENTA cuentan para el tiempo de estanteria; los AJUSTE consumen cola pero
no son operaciones comerciales.

Referencia temporal: la ultima fecha del libro, NO la fecha de ejecucion. Asi el
resultado no cambia por volver a correr el pipeline mas tarde.
"""
from collections import deque

TIPOS_ENTRADA = {"APERTURA", "COMPRA"}
TIPOS_SALIDA  = {"VENTA", "AJUSTE"}
TIPOS_VENTA   = {"VENTA"}


def fifo_producto(fechas, tipos, cantidades, cortes, fecha_corte_datos):
    """Devuelve (resumen, snapshots mensuales) de un producto."""
    cola = deque()
    dias_x_unidad = 0.0
    unidades_vendidas = 0.0
    unidades_sin_capa = 0.0
    snapshots = []
    i = 0
    n = len(fechas)

    def foto(corte):
        tot = acum = 0.0
        for f_ent, cant in cola:
            tot  += cant
            acum += cant * (corte - f_ent).astype("timedelta64[D]").astype(float)
        return tot, (acum / tot if tot > 0 else np.nan)

    def procesar_hasta(limite):
        nonlocal i, dias_x_unidad, unidades_vendidas, unidades_sin_capa
        while i < n and fechas[i] <= limite:
            tipo, cant = tipos[i], cantidades[i]
            if tipo in TIPOS_ENTRADA:
                if cant > 0:
                    cola.append([fechas[i], cant])
            elif tipo in TIPOS_SALIDA:
                por_consumir = cant
                es_venta = tipo in TIPOS_VENTA
                while por_consumir > 1e-9 and cola:
                    f_ent, disp = cola[0]
                    usado = min(disp, por_consumir)
                    if es_venta:
                        dias = (fechas[i] - f_ent).astype("timedelta64[D]").astype(float)
                        dias_x_unidad += usado * max(dias, 0.0)
                        unidades_vendidas += usado
                    por_consumir -= usado
                    if disp - usado <= 1e-9:
                        cola.popleft()
                    else:
                        cola[0][1] = disp - usado
                if por_consumir > 1e-9:
                    unidades_sin_capa += por_consumir
                    if es_venta:
                        unidades_vendidas += por_consumir
            i += 1

    for corte in cortes:
        procesar_hasta(corte)
        u, edad = foto(corte)
        snapshots.append({"FECHA_CORTE": corte, "UNIDADES": u, "ANTIGUEDAD_DIAS": edad})

    procesar_hasta(fecha_corte_datos)
    u_fin, edad_fin = foto(fecha_corte_datos)
    edades = [((fecha_corte_datos - f).astype("timedelta64[D]").astype(float), c) for f, c in cola]

    return {
        "UNIDADES_EN_COLA": u_fin,
        "ANTIGUEDAD_STOCK_DIAS": edad_fin,
        "DIAS_ESTANTERIA_VENDIDO": (dias_x_unidad / unidades_vendidas if unidades_vendidas > 0 else np.nan),
        "UNIDADES_SIN_CAPA": unidades_sin_capa,
        "_EDADES": edades,
    }, snapshots


# --- Preparar entradas ---
_mv = mov_limpio_df.copy()
_mv["FECHA"] = pd.to_datetime(_mv["FECHA"]).dt.normalize()
_mv["CODIGO"] = _mv["CODIGO"].astype(str).str.strip()
_mv["CANT_ABS"] = _mv["CANTIDAD_SIGNO"].abs()
_mv = _mv.sort_values(["CODIGO", "FECHA"]).reset_index(drop=True)

FECHA_CORTE_DATOS = _mv["FECHA"].max()
print(f"Fecha de corte de los datos: {FECHA_CORTE_DATOS:%Y-%m-%d}")

_cortes_all = pd.date_range(
    _mv["FECHA"].min().to_period("M").to_timestamp("M"),
    FECHA_CORTE_DATOS.to_period("M").to_timestamp("M"),
    freq="ME",
).values.astype("datetime64[D]")

_corte64 = np.datetime64(FECHA_CORTE_DATOS.to_pydatetime(), "D")

_res, _snaps = [], []
for _k, (_cod, _g) in enumerate(_mv.groupby("CODIGO", sort=False), start=1):
    _f = _g["FECHA"].values.astype("datetime64[D]")
    _r, _s = fifo_producto(
        _f, _g["TIPO_TRANSACCION"].to_numpy(dtype=object),
        _g["CANT_ABS"].to_numpy(dtype=float),
        _cortes_all[_cortes_all >= _f[0]], _corte64,
    )
    _r["CODIGO"] = _cod
    _res.append(_r)
    for _x in _s:
        _x["CODIGO"] = _cod
    _snaps.extend(_s)
    if _k % 1000 == 0:
        print(f"[FIFO] {_k} productos...")

fifo_resumen = pd.DataFrame(_res)
fifo_mensual = pd.DataFrame(_snaps)
print(f"[FIFO] Listo: {len(fifo_resumen):,} productos, {len(fifo_mensual):,} registros producto-mes.")

In [ ]:
# --- Valor del inventario repartido por tramo de antiguedad ---
# Usa los mismos cortes que el resto del proyecto (CORTES_DIAS).
_costo = inventario.copy()
_costo["CODIGO"] = _costo["CODIGO"].astype(str).str.strip()
_costo_map = _costo.groupby("CODIGO")["COSTO"].first()

_filas = []
for _r in _res:
    _c = float(_costo_map.get(_r["CODIGO"], np.nan) or 0.0)
    _b = {"VALOR_0_60": 0.0, "VALOR_61_120": 0.0, "VALOR_121_180": 0.0, "VALOR_MAS_180": 0.0}
    for _edad, _cant in _r["_EDADES"]:
        _v = _cant * (_c if np.isfinite(_c) else 0.0)
        if   _edad <= 60:  _b["VALOR_0_60"]     += _v
        elif _edad <= 120: _b["VALOR_61_120"]   += _v
        elif _edad <= 180: _b["VALOR_121_180"]  += _v
        else:              _b["VALOR_MAS_180"]  += _v
    _b["CODIGO"] = _r["CODIGO"]
    _filas.append(_b)

fifo_resumen = fifo_resumen.drop(columns=["_EDADES"]).merge(
    pd.DataFrame(_filas), on="CODIGO", how="left"
)

# --- Cobertura movil: cuanto dura el stock al ritmo de venta reciente ---
_desde = FECHA_CORTE_DATOS - pd.Timedelta(days=VENTANA_COBERTURA)
_vr = ventas_limpio.copy()
_vr["FECHA"] = pd.to_datetime(_vr["FECHA"])
_vr["CODIGO"] = _vr["CODIGO"].astype(str).str.strip()
_uds_ventana = (
    _vr[_vr["FECHA"] > _desde].groupby("CODIGO")["CANTIDAD"].sum()
)

fifo_resumen["UDS_DIA_RECIENTE"] = (
    fifo_resumen["CODIGO"].map(_uds_ventana).fillna(0.0) / VENTANA_COBERTURA
)
fifo_resumen["COBERTURA_DIAS"] = np.where(
    fifo_resumen["UDS_DIA_RECIENTE"] > 0,
    fifo_resumen["UNIDADES_EN_COLA"] / fifo_resumen["UDS_DIA_RECIENTE"].replace(0, np.nan),
    np.nan,   # sin ventas en la ventana: la cobertura no esta definida
)

print(f"Ventana de cobertura: {_desde:%Y-%m-%d} -> {FECHA_CORTE_DATOS:%Y-%m-%d} ({VENTANA_COBERTURA} dias)")
print(f"  productos con venta en la ventana : {int((fifo_resumen['UDS_DIA_RECIENTE'] > 0).sum()):,}")
print(f"  cobertura mediana (dias)          : {fifo_resumen['COBERTURA_DIAS'].median():,.0f}")
print()
print("Antiguedad del stock (dias):")
print(fifo_resumen["ANTIGUEDAD_STOCK_DIAS"].describe().round(1).to_string())

In [ ]:
"""
Rotacion en disponibilidad, para los productos que hoy estan en cero.

Cobertura y antiguedad no sirven cuando el stock es 0: la primera da siempre 0 y
la segunda no existe. La pregunta ahi es otra: cuando SI tuvo mercaderia, se
vendia bien?

    VENTA_MENSUAL_EN_STOCK = unidades vendidas / meses con stock > 0

Se divide entre los meses en que hubo existencias, no entre los meses de
calendario. Asi el producto no queda castigado por los periodos en que el
proveedor no despacho: esos meses simplemente no cuentan.

MESES_AGOTADO distingue lo urgente de lo descontinuado: un producto que se acabo
el mes pasado no es lo mismo que uno que lleva dos anios en cero.
"""

_fm = fifo_mensual.copy()
_fm["CODIGO"] = _fm["CODIGO"].astype(str).str.strip()
_fm = _fm.sort_values(["CODIGO", "FECHA_CORTE"])


def _meses_en_cero_al_final(unidades) -> int:
    """Meses consecutivos sin stock contando hacia atras desde el ultimo cierre."""
    n = 0
    for v in reversed(unidades.tolist()):
        if v > 0:
            break
        n += 1
    return n


disponibilidad = _fm.groupby("CODIGO").agg(
    MESES_TOTALES=("FECHA_CORTE", "size"),
    MESES_CON_STOCK=("UNIDADES", lambda s: int((s > 0).sum())),
)
disponibilidad["MESES_AGOTADO"] = _fm.groupby("CODIGO")["UNIDADES"].apply(_meses_en_cero_al_final)
disponibilidad = disponibilidad.reset_index()

# Unidades vendidas historicas (misma fuente que el resto del proyecto)
_uds = ventas_limpio.copy()
_uds["CODIGO"] = _uds["CODIGO"].astype(str).str.strip()
_uds_tot = _uds.groupby("CODIGO")["CANTIDAD"].sum()

disponibilidad["UDS_VENDIDAS"] = disponibilidad["CODIGO"].map(_uds_tot).fillna(0.0)

disponibilidad["DISPONIBILIDAD_PCT"] = np.where(
    disponibilidad["MESES_TOTALES"] > 0,
    disponibilidad["MESES_CON_STOCK"] / disponibilidad["MESES_TOTALES"] * 100,
    np.nan,
)
disponibilidad["VENTA_MENSUAL_EN_STOCK"] = np.where(
    disponibilidad["MESES_CON_STOCK"] > 0,
    disponibilidad["UDS_VENDIDAS"] / disponibilidad["MESES_CON_STOCK"].replace(0, np.nan),
    np.nan,
)
disponibilidad["UNIDADES_PERDIDAS_EST"] = (
    disponibilidad["VENTA_MENSUAL_EN_STOCK"].fillna(0.0) * disponibilidad["MESES_AGOTADO"]
)

print("== Disponibilidad ==")
print(f"  productos                     : {len(disponibilidad):,}")
print(f"  hoy agotados (>=1 mes en cero): {int((disponibilidad['MESES_AGOTADO'] > 0).sum()):,}")
print(f"  nunca tuvieron stock          : {int((disponibilidad['MESES_CON_STOCK'] == 0).sum()):,}")
print()
print("Venta mensual en disponibilidad (unidades/mes):")
print(disponibilidad["VENTA_MENSUAL_EN_STOCK"].describe(percentiles=[.5, .75, .9]).round(2).to_string())
print()
print("Meses agotado (solo los que estan en cero):")
_ag = disponibilidad.loc[disponibilidad["MESES_AGOTADO"] > 0, "MESES_AGOTADO"]
print(_ag.describe(percentiles=[.25, .5, .75]).round(1).to_string())

### 5.1. EXPORTACION DEL HISTORICO MENSUAL (evolucion)

In [ ]:
"""
Exporta el historico mensual para la seccion "Evolucion mensual" del dashboard.

Grano: un registro por CODIGO x FECHA_CORTE (fin de mes).

La metrica es ANTIGUEDAD_DIAS (FIFO): los dias que lleva parado el stock de ese
producto a ese cierre de mes, ponderado por unidad. Es la MISMA definicion que usa
el resto del panel, para que la foto y la tendencia hablen de lo mismo.
"""

_hist = fifo_mensual.copy()
_hist["CODIGO"] = _hist["CODIGO"].astype(str).str.strip()
_hist["FECHA_CORTE"] = pd.to_datetime(_hist["FECHA_CORTE"]).dt.to_period("M").dt.to_timestamp("M")

# Dimensiones para que los filtros del dashboard funcionen sobre la serie
_dim = (
    resumen_final_real[["CODIGO", "COMERCIO", "CATEGORIA", "SUBCATEGORIA", "MARCA"]]
    .copy()
    .drop_duplicates(subset=["CODIGO"])
)
_dim["CODIGO"] = _dim["CODIGO"].astype(str).str.strip()

df_hist = (
    _hist.merge(_dim, on="CODIGO", how="inner")
         .rename(columns={"UNIDADES": "STOCK_MENSUAL"})
         .sort_values(["CODIGO", "FECHA_CORTE"])
         .drop_duplicates(subset=["CODIGO", "FECHA_CORTE"], keep="last")
         .reset_index(drop=True)
)

COLS_HIST = [
    "CODIGO", "FECHA_CORTE",
    "COMERCIO", "CATEGORIA", "SUBCATEGORIA", "MARCA",
    "STOCK_MENSUAL", "ANTIGUEDAD_DIAS",
]
df_hist = df_hist[COLS_HIST]

for _c in ["STOCK_MENSUAL", "ANTIGUEDAD_DIAS"]:
    df_hist[_c] = pd.to_numeric(df_hist[_c], errors="coerce").astype("float32")
for _c in ["COMERCIO", "CATEGORIA", "SUBCATEGORIA", "MARCA"]:
    df_hist[_c] = df_hist[_c].astype("string").astype("category")

Path(OUTPUT_HIST_PARQUET).parent.mkdir(parents=True, exist_ok=True)
df_hist.to_parquet(
    OUTPUT_HIST_PARQUET, index=False, engine="pyarrow",
    compression="zstd", use_dictionary=True, coerce_timestamps="ms",
)

_mb = os.path.getsize(OUTPUT_HIST_PARQUET) / 1e6
print(
    f"OK -> escrito {OUTPUT_HIST_PARQUET} | filas={len(df_hist):,} | "
    f"productos={df_hist['CODIGO'].nunique():,} | meses={df_hist['FECHA_CORTE'].nunique()} | "
    f"tamano={_mb:.2f} MB"
)
print(f"Rango: {df_hist['FECHA_CORTE'].min():%Y-%m} -> {df_hist['FECHA_CORTE'].max():%Y-%m}")

# 6. ALARMAS

In [64]:
inventario[(inventario.CATEGORIA == "ACCESORIO") & (inventario.STOCK > 0)].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1357 entries, 1 to 6369
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CODIGO     1357 non-null   object
 1   PRODUCTO   1357 non-null   object
 2   MARCA      1357 non-null   object
 3   STOCK      1357 non-null   float64
 4   COSTO      1357 non-null   float64
 5   TOTAL      1357 non-null   float64
 6   PVP        1357 non-null   float64
 7   CATEGORIA  1357 non-null   object
dtypes: float64(4), object(4)
memory usage: 95.4+ KB

In [70]:
ventas_limpio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55640 entries, 0 to 56709
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FECHA                  55640 non-null  datetime64[ns]
 1   CLIENTE                55640 non-null  object
 2   FACTURA                55640 non-null  object
 3   HORA                   55640 non-null  object
 4   CATEGORIA              55640 non-null  object
 5   CODIGO                 55640 non-null  object
 6   PRODUCTO               55640 non-null  object
 7   CANTIDAD               55640 non-null  float64
 8   V_UNITARIO             55640 non-null  float64
 9   DESCUENTO              55640 non-null  float64
 10  IVA                    55640 non-null  float64
 11  V_TOTAL                55640 non-null  float64
 12  COSTO                  55640 non-null  float64
 13  VENDEDOR               55640 non-null  object
 14  COMERCIO               55640 non-null  object
 15  COSTO_TOTAL_UNITARIO   55640 non-null  float64
 16  INGRESO_TOTAL_SIN_IVA  55640 non-null  float64
 17  UTILIDAD               55640 non-null  float64
dtypes: datetime64[ns](1), float64(9), object(8)
memory usage: 8.1+ MB

In [73]:
# Calculate total quantity sold per product
ventas_almacen_maquinarias = ventas_limpio[(ventas_limpio['COMERCIO'] == 'ALMACEN') & (ventas_limpio['CATEGORIA'] == 'MAQUINARIA')]
top_products = ventas_almacen_maquinarias.groupby('PRODUCTO')['CANTIDAD'].sum().sort_values(ascending=False).head(15)
print(top_products)

PRODUCTO
SOLDADORA ALPHA EL8200 MBHX 200 AMP                                         93.0
AMOLADORA BLACK AND DECKER G720-B / 820W                                    71.0
BOMBA DE AGUA TOTAL DE 0.5HP / 370W UTWP13706                               62.0
AMOLADORA ANGULAR BOSCH 4 1/2" GWS 700                                      51.0
BOMBA SUMERGIBLE SHIMGE 1 HP 110V QDX1,5-32-0,75L2                          50.0
ROTOMARTILLO TOTAL SDS PLUS INDUSTRIAL 1500W UTH1153226 850RPM ELECTRICO    49.0
AMOLADORA DEWALT DWE4212 / 1200W                                            45.0
CAFETERA ELECTRICA PISTOLA ROCIADORA 500W / 800ML BP02445                   44.0
CONTROLADOR AUTOMATICO TOTAL PARA BOMBA DE AGUA 22PSI 750W UTWPS101         44.0
AMOLADORA DEWALT DWE4120 / 900W                                             43.0
ROCIADORA CAFETERA ELECTRICA 450W INGCO USPG3508                            43.0
SOLDADORA PTK IW200BV                                                       42.0
GENERADOR A GASOLINA TRX TX-PG2500 2500W                                    40.0
SOLDADORA INGCO INVERTER MMA 160A ING-UMMA16028                             39.0
ROTOMARTILLO PTK 1500W 1 1/2, 10 JOULS, 120V                                39.0
Name: CANTIDAD, dtype: float64

## 4. FUSION FINAL Y EXPORTACION DEL SUMMARY

In [ ]:
# Fusionar antiguedad, cobertura y valor del inventario en el marco a exportar.
# Va al final del pipeline porque FIFO necesita el libro ya reconstruido.
resumen_final_real["CODIGO"] = resumen_final_real["CODIGO"].astype(str).str.strip()
_f = fifo_resumen.copy()
_f["CODIGO"] = _f["CODIGO"].astype(str).str.strip()

resumen_final_real = resumen_final_real.merge(
    _f[["CODIGO", "ANTIGUEDAD_STOCK_DIAS", "DIAS_ESTANTERIA_VENDIDO", "COBERTURA_DIAS",
        "UNIDADES_SIN_CAPA", "VALOR_0_60", "VALOR_61_120", "VALOR_121_180", "VALOR_MAS_180"]],
    on="CODIGO", how="left",
)

_dp = disponibilidad.copy()
_dp["CODIGO"] = _dp["CODIGO"].astype(str).str.strip()
resumen_final_real = resumen_final_real.merge(
    _dp[["CODIGO", "MESES_CON_STOCK", "MESES_AGOTADO", "DISPONIBILIDAD_PCT",
         "VENTA_MENSUAL_EN_STOCK", "UNIDADES_PERDIDAS_EST"]],
    on="CODIGO", how="left",
)
for _c in ["MESES_CON_STOCK", "MESES_AGOTADO", "UNIDADES_PERDIDAS_EST"]:
    resumen_final_real[_c] = resumen_final_real[_c].fillna(0)

# Capital inmovilizado por producto.
# Se usa el COSTO del inventario (no el de la ultima venta), que es el mismo que
# alimenta el reparto por tramo de antiguedad. Asi los dos cuadran entre si.
_ci = inventario.copy()
_ci["CODIGO"] = _ci["CODIGO"].astype(str).str.strip()
_costo_inv = _ci.groupby("CODIGO")["COSTO"].first()

resumen_final_real["COSTO"] = (
    resumen_final_real["CODIGO"].map(_costo_inv)
    .fillna(pd.to_numeric(resumen_final_real["COSTO"], errors="coerce"))
    .fillna(0.0)
)
resumen_final_real["VALOR_STOCK"] = (
    pd.to_numeric(resumen_final_real["STOCK"], errors="coerce").fillna(0.0)
    * resumen_final_real["COSTO"]
)

# Bucket unificado: se calcula sobre la antiguedad del stock, no sobre la
# frecuencia entre ventas. Un producto sin stock no tiene antiguedad (NaN).
resumen_final_real["ROTACION"] = pd.cut(
    resumen_final_real["ANTIGUEDAD_STOCK_DIAS"],
    bins=CORTES_DIAS, labels=ETIQUETAS_DIAS, right=True, include_lowest=True,
)

# Sin stock no hay antiguedad que clasificar. Puede pasar que la cola FIFO tenga
# unidades y el inventario diga 0 (o al reves) en los productos cuyo libro no
# cuadra; manda el inventario, que es el dato verificable.
_sin_stock = pd.to_numeric(resumen_final_real["STOCK"], errors="coerce").fillna(0.0) <= 0
resumen_final_real.loc[_sin_stock, "ROTACION"] = np.nan
resumen_final_real.loc[_sin_stock, "ANTIGUEDAD_STOCK_DIAS"] = np.nan

for _c in ["VALOR_0_60", "VALOR_61_120", "VALOR_121_180", "VALOR_MAS_180", "UNIDADES_SIN_CAPA"]:
    resumen_final_real[_c] = resumen_final_real[_c].fillna(0.0)

# El reparto por tramo sale de la cola FIFO y el capital total sale del inventario.
# En los productos cuyo libro no cuadra ambos difieren, asi que se reescala el
# reparto para que sume exactamente el capital reportado: la distribucion por
# antiguedad la pone FIFO, el monto lo pone el inventario.
_cols_tramo = ["VALOR_0_60", "VALOR_61_120", "VALOR_121_180", "VALOR_MAS_180"]
_suma_tramos = resumen_final_real[_cols_tramo].sum(axis=1)
_factor = np.where(_suma_tramos > 0, resumen_final_real["VALOR_STOCK"] / _suma_tramos.replace(0, np.nan), 0.0)
for _c in _cols_tramo:
    resumen_final_real[_c] = (resumen_final_real[_c] * _factor).fillna(0.0)

_desc = (resumen_final_real[_cols_tramo].sum(axis=1) - resumen_final_real["VALOR_STOCK"]).abs()
print(f"Productos cuyo reparto no cuadra tras reescalar: {int((_desc > 1).sum())}")
print(f"  (son productos con stock pero sin capas FIFO: libro incompleto)")

print("Productos con antiguedad calculada:",
      int(resumen_final_real["ANTIGUEDAD_STOCK_DIAS"].notna().sum()))
print()
print(resumen_final_real["ROTACION"].value_counts(dropna=False).to_string())
print()
_agotados = resumen_final_real[
    (resumen_final_real["STOCK"].fillna(0) <= 0) & (resumen_final_real["MESES_AGOTADO"] > 0)
]
print()
print(f"Productos agotados hoy: {len(_agotados):,}")
print(f"  con rotacion >= 1 unidad/mes cuando tenian stock: "
      f"{int((_agotados['VENTA_MENSUAL_EN_STOCK'] >= 1).sum()):,}")
print()
print(f"Capital inmovilizado total: ${resumen_final_real['VALOR_STOCK'].sum():,.0f}")
print(f"  de mas de 180 dias:       ${resumen_final_real['VALOR_MAS_180'].sum():,.0f}")

## 3. CREACION DEL SUMMARY PARQUET

In [36]:
"""
Convierte textos frecuentes a 'category', normaliza numéricos a float32/Int32
y guarda un Parquet comprimido con Zstandard (rápido y compacto).

Se exporta 'resumen_final_real' (NO 'resumen_final'): es la version que asigna los
costos fijos leidos de 'costos_fijos_historico.xlsx' mes a mes y separados por
ALMACEN/TALLER, en lugar del monto global fijo que usa 'margen_bruto'.

Requisitos:
  - 'resumen_final_real' DataFrame ya calculado
  - 'COLS_APP' definido
  - 'OUTPUT_PARQUET' definido (celda de parámetros)
  - pyarrow instalado (requirements.txt)
"""

# 3.0 Validaciones
if "resumen_final_real" not in globals():
    raise NameError("No encuentro 'resumen_final_real'. Asegúrate de calcularlo antes de esta celda.")

faltantes = [c for c in COLS_APP if c not in resumen_final_real.columns]
if faltantes:
    raise ValueError(f"Faltan columnas en 'resumen_final_real': {faltantes}")

# 3.1 Seleccionar solo columnas necesarias
df_summary = resumen_final_real[COLS_APP].copy()

# 3.2 Normalizar tipos numéricos
num_maybe_float = ["beneficio_promedio_por_producto", "margen_bruto_%"]
num_maybe_int   = ["STOCK", "unidades_vendidas_totales"]

for c in num_maybe_float:
    if c in df_summary.columns:
        df_summary[c] = pd.to_numeric(df_summary[c], errors="coerce").astype("float32")

for c in num_maybe_int:
    if c in df_summary.columns:
        s = pd.to_numeric(df_summary[c], errors="coerce")
        # Si todos los valores no nulos son enteros, usa Int32 (nullable); si no, float32
        if (s.dropna() % 1 == 0).all():
            df_summary[c] = s.astype("Int32")
        else:
            df_summary[c] = s.astype("float32")

# 3.3 Convertir texto repetido a categoría (reduce tamaño)
cat_cols = [
    "CATEGORIA", "SUBCATEGORIA", "MARCA", "COMERCIO",
    "metrica_margen_bruto", "ROTACION", "CALIDAD_DATOS"
]
for c in cat_cols:
    if c in df_summary.columns:
        df_summary[c] = df_summary[c].astype("string").astype("category")

# (Opcional) Si CODIGO/PRODUCTO se repiten muchísimo, descomenta:
# for c in ["CODIGO", "PRODUCTO"]:
#     if c in df_summary.columns:
#         df_summary[c] = df_summary[c].astype("string").astype("category")

# 3.4 Guardar parquet optimizado
Path(OUTPUT_PARQUET).parent.mkdir(parents=True, exist_ok=True)
df_summary.to_parquet(
    OUTPUT_PARQUET,
    index=False,
    engine="pyarrow",
    compression="zstd",       # excelente ratio compresión/velocidad
    use_dictionary=True,      # aprovecha categorías para strings
    coerce_timestamps="ms"    # homogeneiza precisión si aparecen fechas
)

size_mb = os.path.getsize(OUTPUT_PARQUET) / 1e6
print(f"OK -> escrito {OUTPUT_PARQUET} | filas={len(df_summary):,} | tamaño={size_mb:.2f} MB")

# 3.5 Lectura de prueba rápida (para CI)
cols_check = [c for c in [
    "CATEGORIA","SUBCATEGORIA","MARCA","COMERCIO",
    "margen_bruto_%","metrica_margen_bruto","beneficio_promedio_por_producto",
    "STOCK","unidades_vendidas_totales","ANTIGUEDAD_STOCK_DIAS","VALOR_STOCK"
] if c in df_summary.columns]

test = pd.read_parquet(OUTPUT_PARQUET, columns=cols_check)
print("Lectura de prueba OK:", test.shape)

print("\nDtypes optimizados:")
print(df_summary.dtypes)

OK -> escrito data/summary.parquet | filas=5,876 | tamaño=0.23 MB
Lectura de prueba OK: (5876, 10)

Dtypes optimizados:
CODIGO                               object
PRODUCTO                             object
CATEGORIA                          category
SUBCATEGORIA                       category
MARCA                              category
COMERCIO                           category
PROMEDIO_DIAS_VENTAS                float32
margen_bruto_%                      float32
metrica_margen_bruto               category
beneficio_promedio_por_producto     float32
STOCK                               float32
unidades_vendidas_totales           float32
TIEMPO_PROMEDIO_VENTAS             category
dtype: object